// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAlert = `-- name: CreateAlert :execlastid
INSERT INTO Alerts (vehicle_id, alert_type, message, is_resolved)
VALUES (?, ?, ?, 0)
`

type CreateAlertParams struct {
	VehicleID sql.NullInt32  `json:"vehicle_id"`
	AlertType string         `json:"alert_type"`
	Message   sql.NullString `json:"message"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAlert, arg.VehicleID, arg.AlertType, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const createFuelAnomalyAlert = `-- name: CreateFuelAnomalyAlert :execlastid
INSERT INTO Alerts (vehicle_id, fuel_log_id, alert_type, message, is_resolved)
VALUES (?, ?, 'fuel_anomaly', ?, 0)
`

type CreateFuelAnomalyAlertParams struct {
	VehicleID sql.NullInt32  `json:"vehicle_id"`
	FuelLogID sql.NullInt32  `json:"fuel_log_id"`
	Message   sql.NullString `json:"message"`
}

func (q *Queries) CreateFuelAnomalyAlert(ctx context.Context, arg CreateFuelAnomalyAlertParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFuelAnomalyAlert, arg.VehicleID, arg.FuelLogID, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getActiveAssignmentVehicleID = `-- name: GetActiveAssignmentVehicleID :one
SELECT vehicle_id
FROM Assignments
WHERE driver_id = ?
  AND assigned_to IS NULL
LIMIT 1
`

func (q *Queries) GetActiveAssignmentVehicleID(ctx context.Context, driverID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getActiveAssignmentVehicleID, driverID)
	var vehicle_id int32
	err := row.Scan(&vehicle_id)
	return vehicle_id, err
}

const listDriversWithExpiringCertificates = `-- name: ListDriversWithExpiringCertificates :many
SELECT driver_id, license_expiry_date, adr_certified, adr_expiry_date
FROM Drivers
WHERE deleted_at IS NULL
  AND (
    (license_expiry_date IS NOT NULL AND license_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY))
    OR (adr_certified = 1 AND adr_expiry_date IS NOT NULL AND adr_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY))
  )
`

type ListDriversWithExpiringCertificatesRow struct {
	DriverID          int32        `json:"driver_id"`
	LicenseExpiryDate sql.NullTime `json:"license_expiry_date"`
	AdrCertified      bool         `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime `json:"adr_expiry_date"`
}

func (q *Queries) ListDriversWithExpiringCertificates(ctx context.Context) ([]ListDriversWithExpiringCertificatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDriversWithExpiringCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriversWithExpiringCertificatesRow
	for rows.Next() {
		var i ListDriversWithExpiringCertificatesRow
		if err := rows.Scan(
			&i.DriverID,
			&i.LicenseExpiryDate,
			&i.AdrCertified,
			&i.AdrExpiryDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
