// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countAssignments = `-- name: CountAssignments :one
SELECT COUNT(*)
FROM Assignments a
JOIN Vehicles v ON v.vehicle_id = a.vehicle_id AND v.deleted_at IS NULL
JOIN Drivers d ON d.driver_id = a.driver_id AND d.deleted_at IS NULL
WHERE (? = 0 OR a.assigned_to IS NULL)
`

func (q *Queries) CountAssignments(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssignments, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :execlastid
INSERT INTO Assignments (vehicle_id, driver_id, assigned_from)
VALUES (?, ?, ?)
`

type CreateAssignmentParams struct {
	VehicleID    int32     `json:"vehicle_id"`
	DriverID     int32     `json:"driver_id"`
	AssignedFrom time.Time `json:"assigned_from"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAssignment, arg.VehicleID, arg.DriverID, arg.AssignedFrom)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const endAssignment = `-- name: EndAssignment :execrows
UPDATE Assignments
SET assigned_to = ?
WHERE assignment_id = ?
  AND assigned_to IS NULL
`

type EndAssignmentParams struct {
	AssignedTo   sql.NullTime `json:"assigned_to"`
	AssignmentID int32        `json:"assignment_id"`
}

func (q *Queries) EndAssignment(ctx context.Context, arg EndAssignmentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, endAssignment, arg.AssignedTo, arg.AssignmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT
  a.assignment_id,
  a.vehicle_id,
  a.driver_id,
  a.assigned_from,
  a.assigned_to,
  v.vin,
  v.brand,
  v.model,
  d.first_name,
  d.last_name
FROM Assignments a
JOIN Vehicles v ON v.vehicle_id = a.vehicle_id
JOIN Drivers d ON d.driver_id = a.driver_id
WHERE a.assignment_id = ?
LIMIT 1
`

type GetAssignmentByIDRow struct {
	AssignmentID int32          `json:"assignment_id"`
	VehicleID    int32          `json:"vehicle_id"`
	DriverID     int32          `json:"driver_id"`
	AssignedFrom time.Time      `json:"assigned_from"`
	AssignedTo   sql.NullTime   `json:"assigned_to"`
	Vin          string         `json:"vin"`
	Brand        sql.NullString `json:"brand"`
	Model        sql.NullString `json:"model"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, assignmentID int32) (GetAssignmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, assignmentID)
	var i GetAssignmentByIDRow
	err := row.Scan(
		&i.AssignmentID,
		&i.VehicleID,
		&i.DriverID,
		&i.AssignedFrom,
		&i.AssignedTo,
		&i.Vin,
		&i.Brand,
		&i.Model,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const hasDriverActiveAssignmentExcludingID = `-- name: HasDriverActiveAssignmentExcludingID :one
SELECT EXISTS(
  SELECT 1
  FROM Assignments
  WHERE driver_id = ?
    AND assigned_to IS NULL
    AND (? = 0 OR assignment_id <> ?)
)
`

type HasDriverActiveAssignmentExcludingIDParams struct {
	DriverID     int32       `json:"driver_id"`
	Column2      interface{} `json:"column_2"`
	AssignmentID int32       `json:"assignment_id"`
}

func (q *Queries) HasDriverActiveAssignmentExcludingID(ctx context.Context, arg HasDriverActiveAssignmentExcludingIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasDriverActiveAssignmentExcludingID, arg.DriverID, arg.Column2, arg.AssignmentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasDriverOverlappingAssignment = `-- name: HasDriverOverlappingAssignment :one
SELECT EXISTS(
  SELECT 1
  FROM Assignments
  WHERE driver_id = ?
    AND assigned_from <= ?
    AND (assigned_to IS NULL OR assigned_to > ?)
)
`

type HasDriverOverlappingAssignmentParams struct {
	DriverID     int32        `json:"driver_id"`
	AssignedFrom time.Time    `json:"assigned_from"`
	AssignedTo   sql.NullTime `json:"assigned_to"`
}

func (q *Queries) HasDriverOverlappingAssignment(ctx context.Context, arg HasDriverOverlappingAssignmentParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasDriverOverlappingAssignment, arg.DriverID, arg.AssignedFrom, arg.AssignedTo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssignments = `-- name: ListAssignments :many
SELECT
  a.assignment_id,
  a.vehicle_id,
  a.driver_id,
  a.assigned_from,
  a.assigned_to,
  v.vin,
  v.brand,
  v.model,
  d.first_name,
  d.last_name
FROM Assignments a
JOIN Vehicles v ON v.vehicle_id = a.vehicle_id AND v.deleted_at IS NULL
JOIN Drivers d ON d.driver_id = a.driver_id AND d.deleted_at IS NULL
WHERE (? = 0 OR a.assigned_to IS NULL)
ORDER BY a.assignment_id DESC
LIMIT ? OFFSET ?
`

type ListAssignmentsParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListAssignmentsRow struct {
	AssignmentID int32          `json:"assignment_id"`
	VehicleID    int32          `json:"vehicle_id"`
	DriverID     int32          `json:"driver_id"`
	AssignedFrom time.Time      `json:"assigned_from"`
	AssignedTo   sql.NullTime   `json:"assigned_to"`
	Vin          string         `json:"vin"`
	Brand        sql.NullString `json:"brand"`
	Model        sql.NullString `json:"model"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
}

func (q *Queries) ListAssignments(ctx context.Context, arg ListAssignmentsParams) ([]ListAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssignments, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsRow
	for rows.Next() {
		var i ListAssignmentsRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.VehicleID,
			&i.DriverID,
			&i.AssignedFrom,
			&i.AssignedTo,
			&i.Vin,
			&i.Brand,
			&i.Model,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
