// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT
  u.user_id,
  u.username,
  r.role_name,
  u.password_hash,
  u.failed_login_attempts,
  u.locked_until
FROM Users u
JOIN Roles r ON r.role_id = u.role_id
WHERE u.username = ?
LIMIT 1
`

type GetUserByLoginRow struct {
	UserID              int32         `json:"user_id"`
	Username            string        `json:"username"`
	RoleName            string        `json:"role_name"`
	PasswordHash        string        `json:"password_hash"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime  `json:"locked_until"`
}

func (q *Queries) GetUserByLogin(ctx context.Context, username string) (GetUserByLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, username)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.RoleName,
		&i.PasswordHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const updateUserLoginState = `-- name: UpdateUserLoginState :exec
UPDATE Users
SET failed_login_attempts = ?, locked_until = ?
WHERE user_id = ?
`

type UpdateUserLoginStateParams struct {
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime  `json:"locked_until"`
	UserID              int32         `json:"user_id"`
}

func (q *Queries) UpdateUserLoginState(ctx context.Context, arg UpdateUserLoginStateParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLoginState, arg.FailedLoginAttempts, arg.LockedUntil, arg.UserID)
	return err
}
