// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cargo.sql

package sqlc

import (
	"context"
)

const orderHasHazardousCargo = `-- name: OrderHasHazardousCargo :one
SELECT EXISTS(
  SELECT 1
  FROM Cargo
  WHERE order_id = ?
    AND cargo_type = 'Hazardous'
)
`

func (q *Queries) OrderHasHazardousCargo(ctx context.Context, orderID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, orderHasHazardousCargo, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
