// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changelog.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countChangelog = `-- name: CountChangelog :one
SELECT COUNT(*)
FROM Changelog
WHERE (? = 0 OR user_id = ?)
  AND (? = '' OR table_name = ?)
  AND (? = '' OR operation = ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` >= ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` <= ?)
`

type CountChangelogParams struct {
	Column1     interface{}        `json:"column_1"`
	UserID      sql.NullInt32      `json:"user_id"`
	Column3     interface{}        `json:"column_3"`
	TableName   string             `json:"table_name"`
	Column5     interface{}        `json:"column_5"`
	Operation   ChangelogOperation `json:"operation"`
	Column7     interface{}        `json:"column_7"`
	Timestamp   sql.NullTime       `json:"timestamp"`
	Column9     interface{}        `json:"column_9"`
	Timestamp_2 sql.NullTime       `json:"timestamp_2"`
}

func (q *Queries) CountChangelog(ctx context.Context, arg CountChangelogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChangelog,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.TableName,
		arg.Column5,
		arg.Operation,
		arg.Column7,
		arg.Timestamp,
		arg.Column9,
		arg.Timestamp_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChangelog = `-- name: ListChangelog :many
SELECT
  id,
  user_id,
  table_name,
  record_id,
  operation,
  old_data,
  new_data,
  ` + "`" + `timestamp` + "`" + `
FROM Changelog
WHERE (? = 0 OR user_id = ?)
  AND (? = '' OR table_name = ?)
  AND (? = '' OR operation = ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` >= ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` <= ?)
ORDER BY ` + "`" + `timestamp` + "`" + ` DESC
LIMIT ? OFFSET ?
`

type ListChangelogParams struct {
	Column1     interface{}        `json:"column_1"`
	UserID      sql.NullInt32      `json:"user_id"`
	Column3     interface{}        `json:"column_3"`
	TableName   string             `json:"table_name"`
	Column5     interface{}        `json:"column_5"`
	Operation   ChangelogOperation `json:"operation"`
	Column7     interface{}        `json:"column_7"`
	Timestamp   sql.NullTime       `json:"timestamp"`
	Column9     interface{}        `json:"column_9"`
	Timestamp_2 sql.NullTime       `json:"timestamp_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListChangelog(ctx context.Context, arg ListChangelogParams) ([]Changelog, error) {
	rows, err := q.db.QueryContext(ctx, listChangelog,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.TableName,
		arg.Column5,
		arg.Operation,
		arg.Column7,
		arg.Timestamp,
		arg.Column9,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Changelog
	for rows.Next() {
		var i Changelog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TableName,
			&i.RecordID,
			&i.Operation,
			&i.OldData,
			&i.NewData,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
