// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: changelog.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const countChangelog = `-- name: CountChangelog :one
SELECT COUNT(*)
FROM Changelog
WHERE (? = 0 OR user_id = ?)
  AND (? = 0 OR record_id = ?)
  AND (? = '' OR table_name = ?)
  AND (? = '' OR operation = ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` >= ?)
  AND (? = 0 OR ` + "`" + `timestamp` + "`" + ` <= ?)
`

type CountChangelogParams struct {
	Column1     interface{}        `json:"column_1"`
	UserID      sql.NullInt32      `json:"user_id"`
	Column3     interface{}        `json:"column_3"`
	RecordID    int32              `json:"record_id"`
	Column5     interface{}        `json:"column_5"`
	TableName   string             `json:"table_name"`
	Column7     interface{}        `json:"column_7"`
	Operation   ChangelogOperation `json:"operation"`
	Column9     interface{}        `json:"column_9"`
	Timestamp   sql.NullTime       `json:"timestamp"`
	Column11    interface{}        `json:"column_11"`
	Timestamp_2 sql.NullTime       `json:"timestamp_2"`
}

func (q *Queries) CountChangelog(ctx context.Context, arg CountChangelogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChangelog,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.RecordID,
		arg.Column5,
		arg.TableName,
		arg.Column7,
		arg.Operation,
		arg.Column9,
		arg.Timestamp,
		arg.Column11,
		arg.Timestamp_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChangelog = `-- name: ListChangelog :many
SELECT
  c.id,
  c.user_id,
  u.username,
  c.table_name,
  c.record_id,
  c.operation,
  c.old_data,
  c.new_data,
  c.` + "`" + `timestamp` + "`" + `
FROM Changelog c
LEFT JOIN Users u ON c.user_id = u.user_id
WHERE (? = 0 OR c.user_id = ?)
  AND (? = 0 OR c.record_id = ?)
  AND (? = '' OR c.table_name = ?)
  AND (? = '' OR c.operation = ?)
  AND (? = 0 OR c.` + "`" + `timestamp` + "`" + ` >= ?)
  AND (? = 0 OR c.` + "`" + `timestamp` + "`" + ` <= ?)
ORDER BY c.` + "`" + `timestamp` + "`" + ` DESC
LIMIT ? OFFSET ?
`

type ListChangelogParams struct {
	Column1     interface{}        `json:"column_1"`
	UserID      sql.NullInt32      `json:"user_id"`
	Column3     interface{}        `json:"column_3"`
	RecordID    int32              `json:"record_id"`
	Column5     interface{}        `json:"column_5"`
	TableName   string             `json:"table_name"`
	Column7     interface{}        `json:"column_7"`
	Operation   ChangelogOperation `json:"operation"`
	Column9     interface{}        `json:"column_9"`
	Timestamp   sql.NullTime       `json:"timestamp"`
	Column11    interface{}        `json:"column_11"`
	Timestamp_2 sql.NullTime       `json:"timestamp_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

type ListChangelogRow struct {
	ID        int32              `json:"id"`
	UserID    sql.NullInt32      `json:"user_id"`
	Username  sql.NullString     `json:"username"`
	TableName string             `json:"table_name"`
	RecordID  int32              `json:"record_id"`
	Operation ChangelogOperation `json:"operation"`
	OldData   json.RawMessage    `json:"old_data"`
	NewData   json.RawMessage    `json:"new_data"`
	Timestamp sql.NullTime       `json:"timestamp"`
}

func (q *Queries) ListChangelog(ctx context.Context, arg ListChangelogParams) ([]ListChangelogRow, error) {
	rows, err := q.db.QueryContext(ctx, listChangelog,
		arg.Column1,
		arg.UserID,
		arg.Column3,
		arg.RecordID,
		arg.Column5,
		arg.TableName,
		arg.Column7,
		arg.Operation,
		arg.Column9,
		arg.Timestamp,
		arg.Column11,
		arg.Timestamp_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangelogRow
	for rows.Next() {
		var i ListChangelogRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TableName,
			&i.RecordID,
			&i.Operation,
			&i.OldData,
			&i.NewData,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
