// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*)
FROM Clients
WHERE (? = 1 OR deleted_at IS NULL)
  AND (
    ? = ''
    OR LOWER(company_name) LIKE CONCAT('%', LOWER(?), '%')
    OR nip LIKE CONCAT('%', ?, '%')
  )
`

type CountClientsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	LOWER   string      `json:"LOWER"`
	CONCAT  interface{} `json:"CONCAT"`
}

func (q *Queries) CountClients(ctx context.Context, arg CountClientsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClients,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.CONCAT,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :execlastid
INSERT INTO Clients (
  company_name,
  nip,
  address,
  contact_email
)
VALUES (?, ?, ?, ?)
`

type CreateClientParams struct {
	CompanyName  string         `json:"company_name"`
	Nip          string         `json:"nip"`
	Address      sql.NullString `json:"address"`
	ContactEmail sql.NullString `json:"contact_email"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createClient,
		arg.CompanyName,
		arg.Nip,
		arg.Address,
		arg.ContactEmail,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getClientByID = `-- name: GetClientByID :one
SELECT
  client_id,
  company_name,
  nip,
  address,
  contact_email,
  deleted_at,
  created_at
FROM Clients
WHERE client_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, clientID int32) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByID, clientID)
	var i Client
	err := row.Scan(
		&i.ClientID,
		&i.CompanyName,
		&i.Nip,
		&i.Address,
		&i.ContactEmail,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeletedClientNIPByID = `-- name: GetDeletedClientNIPByID :one
SELECT nip
FROM Clients
WHERE client_id = ?
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedClientNIPByID(ctx context.Context, clientID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getDeletedClientNIPByID, clientID)
	var nip string
	err := row.Scan(&nip)
	return nip, err
}

const hasActiveClientWithNIPExcludingID = `-- name: HasActiveClientWithNIPExcludingID :one
SELECT EXISTS(
  SELECT 1
  FROM Clients
  WHERE nip = ?
    AND deleted_at IS NULL
    AND client_id <> ?
) AS has_conflict
`

type HasActiveClientWithNIPExcludingIDParams struct {
	Nip      string `json:"nip"`
	ClientID int32  `json:"client_id"`
}

func (q *Queries) HasActiveClientWithNIPExcludingID(ctx context.Context, arg HasActiveClientWithNIPExcludingIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveClientWithNIPExcludingID, arg.Nip, arg.ClientID)
	var has_conflict bool
	err := row.Scan(&has_conflict)
	return has_conflict, err
}

const listClients = `-- name: ListClients :many
SELECT
  client_id,
  company_name,
  nip,
  address,
  contact_email,
  deleted_at,
  created_at
FROM Clients
WHERE (? = 1 OR deleted_at IS NULL)
  AND (
    ? = ''
    OR LOWER(company_name) LIKE CONCAT('%', LOWER(?), '%')
    OR nip LIKE CONCAT('%', ?, '%')
  )
ORDER BY client_id DESC
LIMIT ? OFFSET ?
`

type ListClientsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	LOWER   string      `json:"LOWER"`
	CONCAT  interface{} `json:"CONCAT"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.CONCAT,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ClientID,
			&i.CompanyName,
			&i.Nip,
			&i.Address,
			&i.ContactEmail,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreClientByID = `-- name: RestoreClientByID :execrows
UPDATE Clients
SET deleted_at = NULL
WHERE client_id = ?
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreClientByID(ctx context.Context, clientID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreClientByID, clientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteClient = `-- name: SoftDeleteClient :execrows
UPDATE Clients
SET deleted_at = NOW()
WHERE client_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteClient(ctx context.Context, clientID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteClient, clientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateClient = `-- name: UpdateClient :execrows
UPDATE Clients
SET
  company_name = ?,
  nip = ?,
  address = ?,
  contact_email = ?
WHERE client_id = ?
  AND deleted_at IS NULL
`

type UpdateClientParams struct {
	CompanyName  string         `json:"company_name"`
	Nip          string         `json:"nip"`
	Address      sql.NullString `json:"address"`
	ContactEmail sql.NullString `json:"contact_email"`
	ClientID     int32          `json:"client_id"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateClient,
		arg.CompanyName,
		arg.Nip,
		arg.Address,
		arg.ContactEmail,
		arg.ClientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
