// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countCost = `-- name: CountCost :one
SELECT COUNT(*)
FROM Cost
WHERE (? = 0 OR vehicle_id = ?)
  AND (? = '' OR category = ?)
`

type CountCostParams struct {
	Column1   interface{}  `json:"column_1"`
	VehicleID int32        `json:"vehicle_id"`
	Column3   interface{}  `json:"column_3"`
	Category  CostCategory `json:"category"`
}

func (q *Queries) CountCost(ctx context.Context, arg CountCostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCost,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Category,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCost = `-- name: CreateCost :execlastid
INSERT INTO Cost (
  vehicle_id,
  category,
  amount,
  date,
  description,
  invoice_number
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateCostParams struct {
	VehicleID     int32          `json:"vehicle_id"`
	Category      CostCategory   `json:"category"`
	Amount        string         `json:"amount"`
	Date          time.Time      `json:"date"`
	Description   sql.NullString `json:"description"`
	InvoiceNumber sql.NullString `json:"invoice_number"`
}

func (q *Queries) CreateCost(ctx context.Context, arg CreateCostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCost,
		arg.VehicleID,
		arg.Category,
		arg.Amount,
		arg.Date,
		arg.Description,
		arg.InvoiceNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteCost = `-- name: DeleteCost :execrows
DELETE FROM Cost
WHERE id = ?
`

func (q *Queries) DeleteCost(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCostByID = `-- name: GetCostByID :one
SELECT
  id,
  vehicle_id,
  category,
  amount,
  date,
  description,
  invoice_number,
  created_at
FROM Cost
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetCostByID(ctx context.Context, id int32) (Cost, error) {
	row := q.db.QueryRowContext(ctx, getCostByID, id)
	var i Cost
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Category,
		&i.Amount,
		&i.Date,
		&i.Description,
		&i.InvoiceNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listCost = `-- name: ListCost :many
SELECT
  id,
  vehicle_id,
  category,
  amount,
  date,
  description,
  invoice_number,
  created_at
FROM Cost
WHERE (? = 0 OR vehicle_id = ?)
  AND (? = '' OR category = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListCostParams struct {
	Column1   interface{}  `json:"column_1"`
	VehicleID int32        `json:"vehicle_id"`
	Column3   interface{}  `json:"column_3"`
	Category  CostCategory `json:"category"`
	Limit     int32        `json:"limit"`
	Offset    int32        `json:"offset"`
}

func (q *Queries) ListCost(ctx context.Context, arg ListCostParams) ([]Cost, error) {
	rows, err := q.db.QueryContext(ctx, listCost,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Category,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cost
	for rows.Next() {
		var i Cost
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Category,
			&i.Amount,
			&i.Date,
			&i.Description,
			&i.InvoiceNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCost = `-- name: UpdateCost :execrows
UPDATE Cost
SET
  vehicle_id = ?,
  category = ?,
  amount = ?,
  date = ?,
  description = ?,
  invoice_number = ?
WHERE id = ?
`

type UpdateCostParams struct {
	VehicleID     int32          `json:"vehicle_id"`
	Category      CostCategory   `json:"category"`
	Amount        string         `json:"amount"`
	Date          time.Time      `json:"date"`
	Description   sql.NullString `json:"description"`
	InvoiceNumber sql.NullString `json:"invoice_number"`
	ID            int32          `json:"id"`
}

func (q *Queries) UpdateCost(ctx context.Context, arg UpdateCostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCost,
		arg.VehicleID,
		arg.Category,
		arg.Amount,
		arg.Date,
		arg.Description,
		arg.InvoiceNumber,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
