// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
)

const countActiveOrders = `-- name: CountActiveOrders :one
SELECT COUNT(*)
FROM Orders
WHERE status IN ('New', 'Planned', 'InProgress')
`

func (q *Queries) CountActiveOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVehiclesInService = `-- name: CountVehiclesInService :one
SELECT COUNT(*)
FROM Vehicles
WHERE status = 'Service'
  AND deleted_at IS NULL
`

func (q *Queries) CountVehiclesInService(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVehiclesInService)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentMonthCosts = `-- name: GetCurrentMonthCosts :one
SELECT CAST((
  COALESCE((
    SELECT SUM(fl.total_cost)
    FROM fuel_logs fl
    WHERE DATE_FORMAT(fl.date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0) +
  COALESCE((
    SELECT SUM(m.total_cost_pln)
    FROM Maintenance m
    WHERE m.start_date IS NOT NULL
      AND DATE_FORMAT(m.start_date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0) +
  COALESCE((
    SELECT SUM(c.amount)
    FROM costs c
    WHERE DATE_FORMAT(c.date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0)
) AS SIGNED) AS total_costs
`

func (q *Queries) GetCurrentMonthCosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentMonthCosts)
	var total_costs int64
	err := row.Scan(&total_costs)
	return total_costs, err
}

const getCurrentMonthRevenue = `-- name: GetCurrentMonthRevenue :one
SELECT COALESCE(SUM(o.total_price_pln), 0) AS total_revenue
FROM Orders o
WHERE DATE_FORMAT(o.creation_date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
`

func (q *Queries) GetCurrentMonthRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCurrentMonthRevenue)
	var total_revenue interface{}
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const listExpiringInsuranceAlerts = `-- name: ListExpiringInsuranceAlerts :many
SELECT
  'insurance_expiry' AS type,
  CONCAT('Insurance policy for vehicle ', v.vin, ' expires on ', DATE_FORMAT(ip.end_date, '%Y-%m-%d')) AS message
FROM insurance_policies ip
JOIN Vehicles v ON v.vehicle_id = ip.vehicle_id
WHERE ip.end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
  AND v.deleted_at IS NULL
ORDER BY ip.end_date ASC
LIMIT 50
`

type ListExpiringInsuranceAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListExpiringInsuranceAlerts(ctx context.Context) ([]ListExpiringInsuranceAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringInsuranceAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringInsuranceAlertsRow
	for rows.Next() {
		var i ListExpiringInsuranceAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingInspectionAlerts = `-- name: ListUpcomingInspectionAlerts :many
SELECT
  'inspection_due' AS type,
  CONCAT('Vehicle inspection for ', v.vin, ' scheduled on ', DATE_FORMAT(v.next_inspection_date, '%Y-%m-%d')) AS message
FROM Vehicles v
WHERE v.next_inspection_date IS NOT NULL
  AND v.next_inspection_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
  AND v.deleted_at IS NULL
ORDER BY v.next_inspection_date ASC
LIMIT 50
`

type ListUpcomingInspectionAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListUpcomingInspectionAlerts(ctx context.Context) ([]ListUpcomingInspectionAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingInspectionAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingInspectionAlertsRow
	for rows.Next() {
		var i ListUpcomingInspectionAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringLicenseAlerts = `-- name: ListExpiringLicenseAlerts :many
SELECT
  'license_expiry' AS type,
  CONCAT('Driver license for ', d.first_name, ' ', d.last_name, ' expires on ', DATE_FORMAT(d.license_expiry_date, '%Y-%m-%d')) AS message
FROM Drivers d
WHERE d.deleted_at IS NULL
  AND d.license_expiry_date IS NOT NULL
  AND d.license_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
ORDER BY d.license_expiry_date ASC
LIMIT 50
`

type ListExpiringLicenseAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListExpiringLicenseAlerts(ctx context.Context) ([]ListExpiringLicenseAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringLicenseAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringLicenseAlertsRow
	for rows.Next() {
		var i ListExpiringLicenseAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringAdrAlerts = `-- name: ListExpiringAdrAlerts :many
SELECT
  'adr_expiry' AS type,
  CONCAT('ADR certificate for ', d.first_name, ' ', d.last_name, ' expires on ', DATE_FORMAT(d.adr_expiry_date, '%Y-%m-%d')) AS message
FROM Drivers d
WHERE d.deleted_at IS NULL
  AND d.adr_certified = 1
  AND d.adr_expiry_date IS NOT NULL
  AND d.adr_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
ORDER BY d.adr_expiry_date ASC
LIMIT 50
`

type ListExpiringAdrAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListExpiringAdrAlerts(ctx context.Context) ([]ListExpiringAdrAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringAdrAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringAdrAlertsRow
	for rows.Next() {
		var i ListExpiringAdrAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
