// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
)

const countActiveOrders = `-- name: CountActiveOrders :one
SELECT COUNT(*)
FROM Orders
WHERE status IN ('New', 'Planned', 'InProgress')
`

func (q *Queries) CountActiveOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVehiclesInService = `-- name: CountVehiclesInService :one
SELECT COUNT(*)
FROM Vehicles
WHERE status = 'Service'
  AND deleted_at IS NULL
`

func (q *Queries) CountVehiclesInService(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVehiclesInService)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCurrentMonthCosts = `-- name: GetCurrentMonthCosts :one
SELECT CAST((
  COALESCE((
    SELECT SUM(fl.total_cost)
    FROM fuel_logs fl
    WHERE DATE_FORMAT(fl.date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0) +
  COALESCE((
    SELECT SUM(m.total_cost_pln)
    FROM Maintenance m
    WHERE m.start_date IS NOT NULL
      AND DATE_FORMAT(m.start_date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0) +
  COALESCE((
    SELECT SUM(c.amount)
    FROM costs c
    WHERE DATE_FORMAT(c.date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
  ), 0)
) AS SIGNED) AS total_costs
`

func (q *Queries) GetCurrentMonthCosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentMonthCosts)
	var total_costs int64
	err := row.Scan(&total_costs)
	return total_costs, err
}

const getCurrentMonthRevenue = `-- name: GetCurrentMonthRevenue :one
SELECT COALESCE(SUM(o.total_price_pln), 0) AS total_revenue
FROM Orders o
WHERE DATE_FORMAT(o.creation_date, '%Y-%m') = DATE_FORMAT(CURDATE(), '%Y-%m')
`

func (q *Queries) GetCurrentMonthRevenue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCurrentMonthRevenue)
	var total_revenue interface{}
	err := row.Scan(&total_revenue)
	return total_revenue, err
}

const listExpiringCertificateAlerts = `-- name: ListExpiringCertificateAlerts :many
SELECT
  'certificate_expiry' AS type,
  CONCAT('Certyfikat kierowcy ', d.first_name, ' ', d.last_name, ' wygasa ', DATE_FORMAT(d.expiry_date, '%Y-%m-%d')) AS message
FROM (
  SELECT driver_id, first_name, last_name, license_expiry_date AS expiry_date
  FROM Drivers
  WHERE deleted_at IS NULL
    AND license_expiry_date IS NOT NULL
    AND license_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
  UNION ALL
  SELECT driver_id, first_name, last_name, adr_expiry_date AS expiry_date
  FROM Drivers
  WHERE deleted_at IS NULL
    AND adr_certified = 1
    AND adr_expiry_date IS NOT NULL
    AND adr_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
) d
ORDER BY d.expiry_date ASC
LIMIT 50
`

type ListExpiringCertificateAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListExpiringCertificateAlerts(ctx context.Context) ([]ListExpiringCertificateAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringCertificateAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringCertificateAlertsRow
	for rows.Next() {
		var i ListExpiringCertificateAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringInsuranceAlerts = `-- name: ListExpiringInsuranceAlerts :many
SELECT
  'insurance_expiry' AS type,
  CONCAT('Polisa pojazdu ', v.vin, ' wygasa ', DATE_FORMAT(ip.end_date, '%Y-%m-%d')) AS message
FROM insurance_policies ip
JOIN Vehicles v ON v.vehicle_id = ip.vehicle_id
WHERE ip.end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
  AND v.deleted_at IS NULL
ORDER BY ip.end_date ASC
LIMIT 50
`

type ListExpiringInsuranceAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListExpiringInsuranceAlerts(ctx context.Context) ([]ListExpiringInsuranceAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiringInsuranceAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringInsuranceAlertsRow
	for rows.Next() {
		var i ListExpiringInsuranceAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingInspectionAlerts = `-- name: ListUpcomingInspectionAlerts :many
SELECT
  'inspection_due' AS type,
  CONCAT('Przeglad pojazdu ', v.vin, ' zaplanowany na ', DATE_FORMAT(v.next_inspection_date, '%Y-%m-%d')) AS message
FROM Vehicles v
WHERE v.next_inspection_date IS NOT NULL
  AND v.next_inspection_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 30 DAY)
  AND v.deleted_at IS NULL
ORDER BY v.next_inspection_date ASC
LIMIT 50
`

type ListUpcomingInspectionAlertsRow struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

func (q *Queries) ListUpcomingInspectionAlerts(ctx context.Context) ([]ListUpcomingInspectionAlertsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingInspectionAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingInspectionAlertsRow
	for rows.Next() {
		var i ListUpcomingInspectionAlertsRow
		if err := rows.Scan(&i.Type, &i.Message); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
