// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dictionaries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createDictionary = `-- name: CreateDictionary :execlastid
INSERT INTO Dictionaries (category, ` + "`" + `key` + "`" + `, ` + "`" + `value` + "`" + `)
VALUES (?, ?, ?)
`

type CreateDictionaryParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

func (q *Queries) CreateDictionary(ctx context.Context, arg CreateDictionaryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDictionary, arg.Category, arg.Key, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteDictionary = `-- name: DeleteDictionary :execresult
DELETE FROM Dictionaries
WHERE id = ?
`

func (q *Queries) DeleteDictionary(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteDictionary, id)
}

const getDictionaryByID = `-- name: GetDictionaryByID :one
SELECT
  id,
  category,
  ` + "`" + `key` + "`" + `,
  ` + "`" + `value` + "`" + `,
  created_at
FROM Dictionaries
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetDictionaryByID(ctx context.Context, id int32) (Dictionary, error) {
	row := q.db.QueryRowContext(ctx, getDictionaryByID, id)
	var i Dictionary
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
	)
	return i, err
}

const listDictionariesByCategory = `-- name: ListDictionariesByCategory :many
SELECT
  id,
  category,
  ` + "`" + `key` + "`" + `,
  ` + "`" + `value` + "`" + `,
  created_at
FROM Dictionaries
WHERE category = ?
ORDER BY ` + "`" + `key` + "`" + ` ASC
`

func (q *Queries) ListDictionariesByCategory(ctx context.Context, category string) ([]Dictionary, error) {
	rows, err := q.db.QueryContext(ctx, listDictionariesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dictionary
	for rows.Next() {
		var i Dictionary
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDictionary = `-- name: UpdateDictionary :execresult
UPDATE Dictionaries
SET
  category = ?,
  ` + "`" + `key` + "`" + ` = ?,
  ` + "`" + `value` + "`" + ` = ?
WHERE id = ?
`

type UpdateDictionaryParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
	Value    string `json:"value"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateDictionary(ctx context.Context, arg UpdateDictionaryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateDictionary,
		arg.Category,
		arg.Key,
		arg.Value,
		arg.ID,
	)
}
