// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drivers.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countDrivers = `-- name: CountDrivers :one
SELECT COUNT(*)
FROM Drivers
WHERE (? = 1 OR deleted_at IS NULL)
  AND (? = '' OR LOWER(first_name) LIKE CONCAT('%', LOWER(?), '%') OR LOWER(last_name) LIKE CONCAT('%', LOWER(?), '%'))
  AND (? = '' OR status = ?)
`

type CountDriversParams struct {
	Column1 interface{}       `json:"column_1"`
	Column2 interface{}       `json:"column_2"`
	LOWER   string            `json:"LOWER"`
	LOWER_2 string            `json:"LOWER_2"`
	Column5 interface{}       `json:"column_5"`
	Status  NullDriversStatus `json:"status"`
}

func (q *Queries) CountDrivers(ctx context.Context, arg CountDriversParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDrivers,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.LOWER_2,
		arg.Column5,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriver = `-- name: CreateDriver :execlastid
INSERT INTO Drivers (
  user_id,
  first_name,
  last_name,
  pesel,
  phone,
  email,
  status
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDriverParams struct {
	UserID    sql.NullInt32     `json:"user_id"`
	FirstName string            `json:"first_name"`
	LastName  string            `json:"last_name"`
	Pesel     sql.NullString    `json:"pesel"`
	Phone     sql.NullString    `json:"phone"`
	Email     sql.NullString    `json:"email"`
	Status    NullDriversStatus `json:"status"`
}

func (q *Queries) CreateDriver(ctx context.Context, arg CreateDriverParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createDriver,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Pesel,
		arg.Phone,
		arg.Email,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const forgetDriverByID = `-- name: ForgetDriverByID :execrows
UPDATE Drivers
SET
  user_id = NULL,
  first_name = 'Anonymous',
  last_name = 'Anonymous',
  pesel = NULL,
  phone = NULL,
  email = NULL,
  license_number = NULL,
  license_expiry_date = NULL,
  adr_certified = 0,
  adr_expiry_date = NULL,
  updated_at = NOW()
WHERE driver_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) ForgetDriverByID(ctx context.Context, driverID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, forgetDriverByID, driverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDeletedDriverPESELByID = `-- name: GetDeletedDriverPESELByID :one
SELECT pesel
FROM Drivers
WHERE driver_id = ?
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedDriverPESELByID(ctx context.Context, driverID int32) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getDeletedDriverPESELByID, driverID)
	var pesel sql.NullString
	err := row.Scan(&pesel)
	return pesel, err
}

const getDriverByID = `-- name: GetDriverByID :one
SELECT
  driver_id,
  user_id,
  first_name,
  last_name,
  pesel,
  phone,
  email,
  status,
  license_number,
  license_expiry_date,
  adr_certified,
  adr_expiry_date,
  created_at,
  updated_at
FROM Drivers
WHERE driver_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

type GetDriverByIDRow struct {
	DriverID          int32             `json:"driver_id"`
	UserID            sql.NullInt32     `json:"user_id"`
	FirstName         string            `json:"first_name"`
	LastName          string            `json:"last_name"`
	Pesel             sql.NullString    `json:"pesel"`
	Phone             sql.NullString    `json:"phone"`
	Email             sql.NullString    `json:"email"`
	Status            NullDriversStatus `json:"status"`
	LicenseNumber     sql.NullString    `json:"license_number"`
	LicenseExpiryDate sql.NullTime      `json:"license_expiry_date"`
	AdrCertified      bool              `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime      `json:"adr_expiry_date"`
	CreatedAt         sql.NullTime      `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
}

func (q *Queries) GetDriverByID(ctx context.Context, driverID int32) (GetDriverByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverByID, driverID)
	var i GetDriverByIDRow
	err := row.Scan(
		&i.DriverID,
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Pesel,
		&i.Phone,
		&i.Email,
		&i.Status,
		&i.LicenseNumber,
		&i.LicenseExpiryDate,
		&i.AdrCertified,
		&i.AdrExpiryDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDriverTripOnDate = `-- name: GetDriverTripOnDate :one
SELECT o.order_number
FROM Trips t
JOIN Orders o ON t.order_id = o.order_id
WHERE t.driver_id = ?
  AND t.status IN ('Scheduled', 'Active')
  AND DATE(t.start_time) <= ?
  AND (t.end_time IS NULL OR DATE(t.end_time) >= ?)
LIMIT 1
`

type GetDriverTripOnDateParams struct {
	DriverID  int32        `json:"driver_id"`
	CheckDate sql.NullTime `json:"check_date"`
}

func (q *Queries) GetDriverTripOnDate(ctx context.Context, arg GetDriverTripOnDateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDriverTripOnDate, arg.DriverID, arg.CheckDate, arg.CheckDate)
	var order_number string
	err := row.Scan(&order_number)
	return order_number, err
}

const hasActiveDriverWithPESELExcludingID = `-- name: HasActiveDriverWithPESELExcludingID :one
SELECT EXISTS(
  SELECT 1
  FROM Drivers
  WHERE pesel = ?
    AND deleted_at IS NULL
    AND driver_id <> ?
)
`

type HasActiveDriverWithPESELExcludingIDParams struct {
	Pesel    sql.NullString `json:"pesel"`
	DriverID int32          `json:"driver_id"`
}

func (q *Queries) HasActiveDriverWithPESELExcludingID(ctx context.Context, arg HasActiveDriverWithPESELExcludingIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveDriverWithPESELExcludingID, arg.Pesel, arg.DriverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveTripsByDriverID = `-- name: HasActiveTripsByDriverID :one
SELECT EXISTS(
  SELECT 1
  FROM Trips
  WHERE driver_id = ?
    AND status IN ('Active', 'Scheduled')
)
`

func (q *Queries) HasActiveTripsByDriverID(ctx context.Context, driverID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveTripsByDriverID, driverID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveDriverPESELs = `-- name: ListActiveDriverPESELs :many
SELECT driver_id, pesel
FROM Drivers
WHERE deleted_at IS NULL
`

type ListActiveDriverPESELsRow struct {
	DriverID int32          `json:"driver_id"`
	Pesel    sql.NullString `json:"pesel"`
}

func (q *Queries) ListActiveDriverPESELs(ctx context.Context) ([]ListActiveDriverPESELsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDriverPESELs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDriverPESELsRow
	for rows.Next() {
		var i ListActiveDriverPESELsRow
		if err := rows.Scan(&i.DriverID, &i.Pesel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT
  driver_id,
  user_id,
  first_name,
  last_name,
  pesel,
  phone,
  email,
  status,
  license_number,
  license_expiry_date,
  adr_certified,
  adr_expiry_date,
  deleted_at,
  created_at,
  updated_at
FROM Drivers
WHERE (? = 1 OR deleted_at IS NULL)
  AND (? = '' OR LOWER(first_name) LIKE CONCAT('%', LOWER(?), '%') OR LOWER(last_name) LIKE CONCAT('%', LOWER(?), '%'))
  AND (? = '' OR status = ?)
ORDER BY driver_id DESC
LIMIT ? OFFSET ?
`

type ListDriversParams struct {
	Column1 interface{}       `json:"column_1"`
	Column2 interface{}       `json:"column_2"`
	LOWER   string            `json:"LOWER"`
	LOWER_2 string            `json:"LOWER_2"`
	Column5 interface{}       `json:"column_5"`
	Status  NullDriversStatus `json:"status"`
	Limit   int32             `json:"limit"`
	Offset  int32             `json:"offset"`
}

type ListDriversRow struct {
	DriverID          int32             `json:"driver_id"`
	UserID            sql.NullInt32     `json:"user_id"`
	FirstName         string            `json:"first_name"`
	LastName          string            `json:"last_name"`
	Pesel             sql.NullString    `json:"pesel"`
	Phone             sql.NullString    `json:"phone"`
	Email             sql.NullString    `json:"email"`
	Status            NullDriversStatus `json:"status"`
	LicenseNumber     sql.NullString    `json:"license_number"`
	LicenseExpiryDate sql.NullTime      `json:"license_expiry_date"`
	AdrCertified      bool              `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime      `json:"adr_expiry_date"`
	DeletedAt         sql.NullTime      `json:"deleted_at"`
	CreatedAt         sql.NullTime      `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
}

func (q *Queries) ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrivers,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.LOWER_2,
		arg.Column5,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriversRow
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.DriverID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Pesel,
			&i.Phone,
			&i.Email,
			&i.Status,
			&i.LicenseNumber,
			&i.LicenseExpiryDate,
			&i.AdrCertified,
			&i.AdrExpiryDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriversForPESELSearch = `-- name: ListDriversForPESELSearch :many
SELECT
  driver_id,
  user_id,
  first_name,
  last_name,
  pesel,
  phone,
  email,
  status,
  license_number,
  license_expiry_date,
  adr_certified,
  adr_expiry_date,
  deleted_at,
  created_at,
  updated_at
FROM Drivers
WHERE (? = 1 OR deleted_at IS NULL)
  AND (? = '' OR status = ?)
ORDER BY driver_id DESC
LIMIT 1000
`

type ListDriversForPESELSearchParams struct {
	Column1 interface{}       `json:"column_1"`
	Column2 interface{}       `json:"column_2"`
	Status  NullDriversStatus `json:"status"`
}

type ListDriversForPESELSearchRow struct {
	DriverID          int32             `json:"driver_id"`
	UserID            sql.NullInt32     `json:"user_id"`
	FirstName         string            `json:"first_name"`
	LastName          string            `json:"last_name"`
	Pesel             sql.NullString    `json:"pesel"`
	Phone             sql.NullString    `json:"phone"`
	Email             sql.NullString    `json:"email"`
	Status            NullDriversStatus `json:"status"`
	LicenseNumber     sql.NullString    `json:"license_number"`
	LicenseExpiryDate sql.NullTime      `json:"license_expiry_date"`
	AdrCertified      bool              `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime      `json:"adr_expiry_date"`
	DeletedAt         sql.NullTime      `json:"deleted_at"`
	CreatedAt         sql.NullTime      `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
}

func (q *Queries) ListDriversForPESELSearch(ctx context.Context, arg ListDriversForPESELSearchParams) ([]ListDriversForPESELSearchRow, error) {
	rows, err := q.db.QueryContext(ctx, listDriversForPESELSearch, arg.Column1, arg.Column2, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDriversForPESELSearchRow
	for rows.Next() {
		var i ListDriversForPESELSearchRow
		if err := rows.Scan(
			&i.DriverID,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.Pesel,
			&i.Phone,
			&i.Email,
			&i.Status,
			&i.LicenseNumber,
			&i.LicenseExpiryDate,
			&i.AdrCertified,
			&i.AdrExpiryDate,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDriverByID = `-- name: RestoreDriverByID :execrows
UPDATE Drivers
SET deleted_at = NULL, updated_at = NOW()
WHERE driver_id = ?
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreDriverByID(ctx context.Context, driverID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreDriverByID, driverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteDriver = `-- name: SoftDeleteDriver :execrows
UPDATE Drivers
SET deleted_at = NOW(), updated_at = NOW()
WHERE driver_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDriver(ctx context.Context, driverID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteDriver, driverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDriver = `-- name: UpdateDriver :execrows
UPDATE Drivers
SET
  user_id = ?,
  first_name = ?,
  last_name = ?,
  pesel = ?,
  phone = ?,
  email = ?,
  status = ?,
  license_number = ?,
  license_expiry_date = ?,
  adr_certified = ?,
  adr_expiry_date = ?,
  updated_at = NOW()
WHERE driver_id = ?
  AND deleted_at IS NULL
`

type UpdateDriverParams struct {
	UserID            sql.NullInt32     `json:"user_id"`
	FirstName         string            `json:"first_name"`
	LastName          string            `json:"last_name"`
	Pesel             sql.NullString    `json:"pesel"`
	Phone             sql.NullString    `json:"phone"`
	Email             sql.NullString    `json:"email"`
	Status            NullDriversStatus `json:"status"`
	LicenseNumber     sql.NullString    `json:"license_number"`
	LicenseExpiryDate sql.NullTime      `json:"license_expiry_date"`
	AdrCertified      bool              `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime      `json:"adr_expiry_date"`
	DriverID          int32             `json:"driver_id"`
}

func (q *Queries) UpdateDriver(ctx context.Context, arg UpdateDriverParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDriver,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.Pesel,
		arg.Phone,
		arg.Email,
		arg.Status,
		arg.LicenseNumber,
		arg.LicenseExpiryDate,
		arg.AdrCertified,
		arg.AdrExpiryDate,
		arg.DriverID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
