// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fuel.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createFuelLog = `-- name: CreateFuelLog :execlastid
INSERT INTO fuel_logs (
  vehicle_id,
  date,
  liters,
  price_per_liter,
  total_cost,
  mileage,
  location
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFuelLogParams struct {
	VehicleID     int32     `json:"vehicle_id"`
	Date          time.Time `json:"date"`
	Liters        string    `json:"liters"`
	PricePerLiter string    `json:"price_per_liter"`
	TotalCost     string    `json:"total_cost"`
	Mileage       uint32    `json:"mileage"`
	Location      string    `json:"location"`
}

func (q *Queries) CreateFuelLog(ctx context.Context, arg CreateFuelLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFuelLog,
		arg.VehicleID,
		arg.Date,
		arg.Liters,
		arg.PricePerLiter,
		arg.TotalCost,
		arg.Mileage,
		arg.Location,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAvgFuelConsumptionPer100Km = `-- name: GetAvgFuelConsumptionPer100Km :one
SELECT
  AVG(
    CASE
      WHEN prev_mileage IS NULL OR (mileage - prev_mileage) <= 0 THEN NULL
      ELSE (CAST(liters AS DOUBLE) / (mileage - prev_mileage)) * 100
    END
  ) AS avg_consumption_per_100km
FROM (
  SELECT
    liters,
    mileage,
    LAG(mileage) OVER (PARTITION BY vehicle_id ORDER BY date, id) AS prev_mileage
  FROM fuel_logs
  WHERE vehicle_id = ?
) AS x
`

// Avg current consumption across entire fuel history (norm).
// Uses LAG to get previous mileage per log; excludes first log (prev is NULL) and non-positive deltas.
func (q *Queries) GetAvgFuelConsumptionPer100Km(ctx context.Context, vehicleID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAvgFuelConsumptionPer100Km, vehicleID)
	var avg_consumption_per_100km interface{}
	err := row.Scan(&avg_consumption_per_100km)
	return avg_consumption_per_100km, err
}

const getVehicleCurrentMileage = `-- name: GetVehicleCurrentMileage :one
SELECT current_mileage_km
FROM Vehicles
WHERE vehicle_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetVehicleCurrentMileage(ctx context.Context, vehicleID int32) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getVehicleCurrentMileage, vehicleID)
	var current_mileage_km sql.NullInt32
	err := row.Scan(&current_mileage_km)
	return current_mileage_km, err
}

const updateVehicleMileage = `-- name: UpdateVehicleMileage :execrows
UPDATE Vehicles
SET
  current_mileage_km = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleMileageParams struct {
	CurrentMileageKm sql.NullInt32 `json:"current_mileage_km"`
	VehicleID        int32         `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicleMileage(ctx context.Context, arg UpdateVehicleMileageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicleMileage, arg.CurrentMileageKm, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
