// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fuel.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countFuelLogs = `-- name: CountFuelLogs :one
SELECT COUNT(*)
FROM fuel_logs
WHERE (? = 0 OR vehicle_id = ?)
  AND (? = '' OR date >= ?)
  AND (? = '' OR date <= ?)
`

type CountFuelLogsParams struct {
	Column1   interface{} `json:"column_1"`
	VehicleID int32       `json:"vehicle_id"`
	Column3   interface{} `json:"column_3"`
	Date      time.Time   `json:"date"`
	Column5   interface{} `json:"column_5"`
	Date_2    time.Time   `json:"date_2"`
}

func (q *Queries) CountFuelLogs(ctx context.Context, arg CountFuelLogsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFuelLogs,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Date,
		arg.Column5,
		arg.Date_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFuelLog = `-- name: CreateFuelLog :execlastid
INSERT INTO fuel_logs (
  vehicle_id,
  date,
  liters,
  price_per_liter,
  total_cost,
  mileage,
  location
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFuelLogParams struct {
	VehicleID     int32     `json:"vehicle_id"`
	Date          time.Time `json:"date"`
	Liters        string    `json:"liters"`
	PricePerLiter string    `json:"price_per_liter"`
	TotalCost     string    `json:"total_cost"`
	Mileage       uint32    `json:"mileage"`
	Location      string    `json:"location"`
}

func (q *Queries) CreateFuelLog(ctx context.Context, arg CreateFuelLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createFuelLog,
		arg.VehicleID,
		arg.Date,
		arg.Liters,
		arg.PricePerLiter,
		arg.TotalCost,
		arg.Mileage,
		arg.Location,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAvgFuelConsumptionPer100Km = `-- name: GetAvgFuelConsumptionPer100Km :one
SELECT
  AVG(
    CASE
      WHEN prev_mileage IS NULL OR (mileage - prev_mileage) <= 0 THEN NULL
      ELSE (CAST(liters AS DOUBLE) / (mileage - prev_mileage)) * 100
    END
  ) AS avg_consumption_per_100km
FROM (
  SELECT
    liters,
    mileage,
    LAG(mileage) OVER (PARTITION BY vehicle_id ORDER BY date, id) AS prev_mileage
  FROM fuel_logs
  WHERE vehicle_id = ?
) AS x
`

// Avg current consumption across entire fuel history (norm).
// Uses LAG to get previous mileage per log; excludes first log (prev is NULL) and non-positive deltas.
func (q *Queries) GetAvgFuelConsumptionPer100Km(ctx context.Context, vehicleID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAvgFuelConsumptionPer100Km, vehicleID)
	var avg_consumption_per_100km interface{}
	err := row.Scan(&avg_consumption_per_100km)
	return avg_consumption_per_100km, err
}

const getVehicleCurrentMileage = `-- name: GetVehicleCurrentMileage :one
SELECT current_mileage_km
FROM Vehicles
WHERE vehicle_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetVehicleCurrentMileage(ctx context.Context, vehicleID int32) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getVehicleCurrentMileage, vehicleID)
	var current_mileage_km sql.NullInt32
	err := row.Scan(&current_mileage_km)
	return current_mileage_km, err
}

const listFuelLogs = `-- name: ListFuelLogs :many
SELECT
  id,
  vehicle_id,
  date,
  liters,
  price_per_liter,
  total_cost,
  mileage,
  location,
  created_at,
  EXISTS(
    SELECT 1
    FROM Alerts a
    WHERE a.vehicle_id = fuel_logs.vehicle_id
      AND a.fuel_log_id = fuel_logs.id
      AND a.alert_type = 'fuel_anomaly'
  ) AS has_alert
FROM fuel_logs
WHERE (? = 0 OR fuel_logs.vehicle_id = ?)
  AND (? = '' OR fuel_logs.date >= ?)
  AND (? = '' OR fuel_logs.date <= ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListFuelLogsParams struct {
	Column1   interface{} `json:"column_1"`
	VehicleID int32       `json:"vehicle_id"`
	Column3   interface{} `json:"column_3"`
	Date      time.Time   `json:"date"`
	Column5   interface{} `json:"column_5"`
	Date_2    time.Time   `json:"date_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListFuelLogsRow struct {
	ID            int32        `json:"id"`
	VehicleID     int32        `json:"vehicle_id"`
	Date          time.Time    `json:"date"`
	Liters        string       `json:"liters"`
	PricePerLiter string       `json:"price_per_liter"`
	TotalCost     string       `json:"total_cost"`
	Mileage       uint32       `json:"mileage"`
	Location      string       `json:"location"`
	CreatedAt     sql.NullTime `json:"created_at"`
	HasAlert      bool         `json:"has_alert"`
}

func (q *Queries) ListFuelLogs(ctx context.Context, arg ListFuelLogsParams) ([]ListFuelLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFuelLogs,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Date,
		arg.Column5,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFuelLogsRow
	for rows.Next() {
		var i ListFuelLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Date,
			&i.Liters,
			&i.PricePerLiter,
			&i.TotalCost,
			&i.Mileage,
			&i.Location,
			&i.CreatedAt,
			&i.HasAlert,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleMileage = `-- name: UpdateVehicleMileage :execrows
UPDATE Vehicles
SET
  current_mileage_km = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleMileageParams struct {
	CurrentMileageKm sql.NullInt32 `json:"current_mileage_km"`
	VehicleID        int32         `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicleMileage(ctx context.Context, arg UpdateVehicleMileageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicleMileage, arg.CurrentMileageKm, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
