// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insurance.sql

package sqlc

import (
	"context"
	"time"
)

const countInsurancePolicies = `-- name: CountInsurancePolicies :one
SELECT COUNT(*)
FROM insurance_policies
WHERE (? = 0 OR vehicle_id = ?)
`

type CountInsurancePoliciesParams struct {
	Column1   interface{} `json:"column_1"`
	VehicleID int32       `json:"vehicle_id"`
}

func (q *Queries) CountInsurancePolicies(ctx context.Context, arg CountInsurancePoliciesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInsurancePolicies, arg.Column1, arg.VehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInsurancePolicy = `-- name: CreateInsurancePolicy :execlastid
INSERT INTO insurance_policies (
  vehicle_id,
  type,
  policy_number,
  insurer,
  start_date,
  end_date,
  cost
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateInsurancePolicyParams struct {
	VehicleID    int32                 `json:"vehicle_id"`
	Type         InsurancePoliciesType `json:"type"`
	PolicyNumber string                `json:"policy_number"`
	Insurer      string                `json:"insurer"`
	StartDate    time.Time             `json:"start_date"`
	EndDate      time.Time             `json:"end_date"`
	Cost         string                `json:"cost"`
}

func (q *Queries) CreateInsurancePolicy(ctx context.Context, arg CreateInsurancePolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createInsurancePolicy,
		arg.VehicleID,
		arg.Type,
		arg.PolicyNumber,
		arg.Insurer,
		arg.StartDate,
		arg.EndDate,
		arg.Cost,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteInsurancePolicy = `-- name: DeleteInsurancePolicy :execrows
DELETE FROM insurance_policies
WHERE id = ?
`

func (q *Queries) DeleteInsurancePolicy(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInsurancePolicy, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInsurancePolicyByID = `-- name: GetInsurancePolicyByID :one
SELECT
  id,
  vehicle_id,
  type,
  policy_number,
  insurer,
  start_date,
  end_date,
  cost,
  created_at,
  updated_at
FROM insurance_policies
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetInsurancePolicyByID(ctx context.Context, id int32) (InsurancePolicy, error) {
	row := q.db.QueryRowContext(ctx, getInsurancePolicyByID, id)
	var i InsurancePolicy
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Type,
		&i.PolicyNumber,
		&i.Insurer,
		&i.StartDate,
		&i.EndDate,
		&i.Cost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInsurancePolicies = `-- name: ListInsurancePolicies :many
SELECT
  id,
  vehicle_id,
  type,
  policy_number,
  insurer,
  start_date,
  end_date,
  cost,
  created_at,
  updated_at
FROM insurance_policies
WHERE (? = 0 OR vehicle_id = ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListInsurancePoliciesParams struct {
	Column1   interface{} `json:"column_1"`
	VehicleID int32       `json:"vehicle_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListInsurancePolicies(ctx context.Context, arg ListInsurancePoliciesParams) ([]InsurancePolicy, error) {
	rows, err := q.db.QueryContext(ctx, listInsurancePolicies,
		arg.Column1,
		arg.VehicleID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsurancePolicy
	for rows.Next() {
		var i InsurancePolicy
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Type,
			&i.PolicyNumber,
			&i.Insurer,
			&i.StartDate,
			&i.EndDate,
			&i.Cost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsurancePolicy = `-- name: UpdateInsurancePolicy :execrows
UPDATE insurance_policies
SET
  vehicle_id = ?,
  type = ?,
  policy_number = ?,
  insurer = ?,
  start_date = ?,
  end_date = ?,
  cost = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateInsurancePolicyParams struct {
	VehicleID    int32                 `json:"vehicle_id"`
	Type         InsurancePoliciesType `json:"type"`
	PolicyNumber string                `json:"policy_number"`
	Insurer      string                `json:"insurer"`
	StartDate    time.Time             `json:"start_date"`
	EndDate      time.Time             `json:"end_date"`
	Cost         string                `json:"cost"`
	ID           int32                 `json:"id"`
}

func (q *Queries) UpdateInsurancePolicy(ctx context.Context, arg UpdateInsurancePolicyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInsurancePolicy,
		arg.VehicleID,
		arg.Type,
		arg.PolicyNumber,
		arg.Insurer,
		arg.StartDate,
		arg.EndDate,
		arg.Cost,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
