// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: maintenance.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countMaintenance = `-- name: CountMaintenance :one
SELECT COUNT(*)
FROM Maintenance
WHERE (? = 0 OR vehicle_id = ?)
  AND (? = '' OR status = ?)
`

type CountMaintenanceParams struct {
	Column1   interface{}       `json:"column_1"`
	VehicleID int32             `json:"vehicle_id"`
	Column3   interface{}       `json:"column_3"`
	Status    MaintenanceStatus `json:"status"`
}

func (q *Queries) CountMaintenance(ctx context.Context, arg CountMaintenanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaintenance,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenance = `-- name: CreateMaintenance :execlastid
INSERT INTO Maintenance (
  vehicle_id,
  start_date,
  end_date,
  type,
  status,
  description,
  labor_cost_pln,
  parts_cost_pln
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMaintenanceParams struct {
	VehicleID    int32             `json:"vehicle_id"`
	StartDate    sql.NullTime      `json:"start_date"`
	EndDate      sql.NullTime      `json:"end_date"`
	Type         MaintenanceType   `json:"type"`
	Status       MaintenanceStatus `json:"status"`
	Description  sql.NullString    `json:"description"`
	LaborCostPln string            `json:"labor_cost_pln"`
	PartsCostPln string            `json:"parts_cost_pln"`
}

func (q *Queries) CreateMaintenance(ctx context.Context, arg CreateMaintenanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMaintenance,
		arg.VehicleID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Status,
		arg.Description,
		arg.LaborCostPln,
		arg.PartsCostPln,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getMaintenanceByID = `-- name: GetMaintenanceByID :one
SELECT
  maintenance_id,
  vehicle_id,
  start_date,
  end_date,
  type,
  status,
  description,
  labor_cost_pln,
  parts_cost_pln,
  total_cost_pln,
  created_at,
  updated_at
FROM Maintenance
WHERE maintenance_id = ?
LIMIT 1
`

func (q *Queries) GetMaintenanceByID(ctx context.Context, maintenanceID int32) (Maintenance, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceByID, maintenanceID)
	var i Maintenance
	err := row.Scan(
		&i.MaintenanceID,
		&i.VehicleID,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Status,
		&i.Description,
		&i.LaborCostPln,
		&i.PartsCostPln,
		&i.TotalCostPln,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMaintenance = `-- name: ListMaintenance :many
SELECT
  maintenance_id,
  vehicle_id,
  start_date,
  end_date,
  type,
  status,
  description,
  labor_cost_pln,
  parts_cost_pln,
  total_cost_pln,
  created_at,
  updated_at
FROM Maintenance
WHERE (? = 0 OR vehicle_id = ?)
  AND (? = '' OR status = ?)
ORDER BY maintenance_id DESC
LIMIT ? OFFSET ?
`

type ListMaintenanceParams struct {
	Column1   interface{}       `json:"column_1"`
	VehicleID int32             `json:"vehicle_id"`
	Column3   interface{}       `json:"column_3"`
	Status    MaintenanceStatus `json:"status"`
	Limit     int32             `json:"limit"`
	Offset    int32             `json:"offset"`
}

func (q *Queries) ListMaintenance(ctx context.Context, arg ListMaintenanceParams) ([]Maintenance, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenance,
		arg.Column1,
		arg.VehicleID,
		arg.Column3,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Maintenance
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.MaintenanceID,
			&i.VehicleID,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.Status,
			&i.Description,
			&i.LaborCostPln,
			&i.PartsCostPln,
			&i.TotalCostPln,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenance = `-- name: UpdateMaintenance :execrows
UPDATE Maintenance
SET
  vehicle_id = ?,
  start_date = ?,
  end_date = ?,
  type = ?,
  status = ?,
  description = ?,
  labor_cost_pln = ?,
  parts_cost_pln = ?,
  updated_at = NOW()
WHERE maintenance_id = ?
`

type UpdateMaintenanceParams struct {
	VehicleID     int32             `json:"vehicle_id"`
	StartDate     sql.NullTime      `json:"start_date"`
	EndDate       sql.NullTime      `json:"end_date"`
	Type          MaintenanceType   `json:"type"`
	Status        MaintenanceStatus `json:"status"`
	Description   sql.NullString    `json:"description"`
	LaborCostPln  string            `json:"labor_cost_pln"`
	PartsCostPln  string            `json:"parts_cost_pln"`
	MaintenanceID int32             `json:"maintenance_id"`
}

func (q *Queries) UpdateMaintenance(ctx context.Context, arg UpdateMaintenanceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMaintenance,
		arg.VehicleID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Status,
		arg.Description,
		arg.LaborCostPln,
		arg.PartsCostPln,
		arg.MaintenanceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMaintenanceStatus = `-- name: UpdateMaintenanceStatus :execrows
UPDATE Maintenance
SET
  status = ?,
  end_date = CASE WHEN ? = 'Completed' THEN NOW() ELSE end_date END,
  updated_at = NOW()
WHERE maintenance_id = ?
`

type UpdateMaintenanceStatusParams struct {
	Status        MaintenanceStatus `json:"status"`
	Column2       interface{}       `json:"column_2"`
	MaintenanceID int32             `json:"maintenance_id"`
}

func (q *Queries) UpdateMaintenanceStatus(ctx context.Context, arg UpdateMaintenanceStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMaintenanceStatus, arg.Status, arg.Column2, arg.MaintenanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
