// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type DriversStatus string

const (
	DriversStatusAvailable DriversStatus = "Available"
	DriversStatusOnLeave   DriversStatus = "OnLeave"
	DriversStatusInRoute   DriversStatus = "InRoute"
)

func (e *DriversStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriversStatus(s)
	case string:
		*e = DriversStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DriversStatus: %T", src)
	}
	return nil
}

type NullDriversStatus struct {
	DriversStatus DriversStatus `json:"drivers_status"`
	Valid         bool          `json:"valid"` // Valid is true if DriversStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriversStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DriversStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriversStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriversStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriversStatus), nil
}

type TripsStatus string

const (
	TripsStatusScheduled TripsStatus = "Scheduled"
	TripsStatusActive    TripsStatus = "Active"
	TripsStatusFinished  TripsStatus = "Finished"
	TripsStatusAborted   TripsStatus = "Aborted"
)

func (e *TripsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripsStatus(s)
	case string:
		*e = TripsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripsStatus: %T", src)
	}
	return nil
}

type NullTripsStatus struct {
	TripsStatus TripsStatus `json:"trips_status"`
	Valid       bool        `json:"valid"` // Valid is true if TripsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripsStatus), nil
}

type VehiclesStatus string

const (
	VehiclesStatusAvailable VehiclesStatus = "Available"
	VehiclesStatusInRoute   VehiclesStatus = "InRoute"
	VehiclesStatusService   VehiclesStatus = "Service"
	VehiclesStatusInactive  VehiclesStatus = "Inactive"
)

func (e *VehiclesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehiclesStatus(s)
	case string:
		*e = VehiclesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VehiclesStatus: %T", src)
	}
	return nil
}

type NullVehiclesStatus struct {
	VehiclesStatus VehiclesStatus `json:"vehicles_status"`
	Valid          bool           `json:"valid"` // Valid is true if VehiclesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehiclesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VehiclesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehiclesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehiclesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehiclesStatus), nil
}

type Driver struct {
	DriverID  int32             `json:"driver_id"`
	UserID    sql.NullInt32     `json:"user_id"`
	FirstName string            `json:"first_name"`
	LastName  string            `json:"last_name"`
	Pesel     string            `json:"pesel"`
	Phone     sql.NullString    `json:"phone"`
	Email     sql.NullString    `json:"email"`
	Status    NullDriversStatus `json:"status"`
	DeletedAt sql.NullTime      `json:"deleted_at"`
	CreatedAt sql.NullTime      `json:"created_at"`
	UpdatedAt sql.NullTime      `json:"updated_at"`
}

type Role struct {
	RoleID      int32          `json:"role_id"`
	RoleName    string         `json:"role_name"`
	Description sql.NullString `json:"description"`
}

type Trip struct {
	TripID    int32       `json:"trip_id"`
	VehicleID int32       `json:"vehicle_id"`
	Status    TripsStatus `json:"status"`
}

type User struct {
	UserID              int32         `json:"user_id"`
	RoleID              int32         `json:"role_id"`
	Username            string        `json:"username"`
	PasswordHash        string        `json:"password_hash"`
	Email               string        `json:"email"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	IsActive            sql.NullBool  `json:"is_active"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime  `json:"locked_until"`
}

type Vehicle struct {
	VehicleID        int32              `json:"vehicle_id"`
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	ProductionYear   sql.NullInt16      `json:"production_year"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	DeletedAt        sql.NullTime       `json:"deleted_at"`
	CreatedAt        sql.NullTime       `json:"created_at"`
	UpdatedAt        sql.NullTime       `json:"updated_at"`
}
