// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CargoCargoType string

const (
	CargoCargoTypeGeneral      CargoCargoType = "General"
	CargoCargoTypeRefrigerated CargoCargoType = "Refrigerated"
	CargoCargoTypeHazardous    CargoCargoType = "Hazardous"
)

func (e *CargoCargoType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CargoCargoType(s)
	case string:
		*e = CargoCargoType(s)
	default:
		return fmt.Errorf("unsupported scan type for CargoCargoType: %T", src)
	}
	return nil
}

type NullCargoCargoType struct {
	CargoCargoType CargoCargoType `json:"cargo_cargo_type"`
	Valid          bool           `json:"valid"` // Valid is true if CargoCargoType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCargoCargoType) Scan(value interface{}) error {
	if value == nil {
		ns.CargoCargoType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CargoCargoType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCargoCargoType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CargoCargoType), nil
}

type DriversStatus string

const (
	DriversStatusAvailable DriversStatus = "Available"
	DriversStatusOnLeave   DriversStatus = "OnLeave"
	DriversStatusInRoute   DriversStatus = "InRoute"
)

func (e *DriversStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriversStatus(s)
	case string:
		*e = DriversStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DriversStatus: %T", src)
	}
	return nil
}

type NullDriversStatus struct {
	DriversStatus DriversStatus `json:"drivers_status"`
	Valid         bool          `json:"valid"` // Valid is true if DriversStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriversStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DriversStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriversStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriversStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriversStatus), nil
}

type OrdersStatus string

const (
	OrdersStatusNew        OrdersStatus = "New"
	OrdersStatusPlanned    OrdersStatus = "Planned"
	OrdersStatusInProgress OrdersStatus = "InProgress"
	OrdersStatusCompleted  OrdersStatus = "Completed"
	OrdersStatusCancelled  OrdersStatus = "Cancelled"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type TripsStatus string

const (
	TripsStatusScheduled TripsStatus = "Scheduled"
	TripsStatusActive    TripsStatus = "Active"
	TripsStatusFinished  TripsStatus = "Finished"
	TripsStatusAborted   TripsStatus = "Aborted"
)

func (e *TripsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripsStatus(s)
	case string:
		*e = TripsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripsStatus: %T", src)
	}
	return nil
}

type NullTripsStatus struct {
	TripsStatus TripsStatus `json:"trips_status"`
	Valid       bool        `json:"valid"` // Valid is true if TripsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripsStatus), nil
}

type VehiclesStatus string

const (
	VehiclesStatusAvailable VehiclesStatus = "Available"
	VehiclesStatusInRoute   VehiclesStatus = "InRoute"
	VehiclesStatusService   VehiclesStatus = "Service"
	VehiclesStatusInactive  VehiclesStatus = "Inactive"
)

func (e *VehiclesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehiclesStatus(s)
	case string:
		*e = VehiclesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VehiclesStatus: %T", src)
	}
	return nil
}

type NullVehiclesStatus struct {
	VehiclesStatus VehiclesStatus `json:"vehicles_status"`
	Valid          bool           `json:"valid"` // Valid is true if VehiclesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehiclesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VehiclesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehiclesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehiclesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehiclesStatus), nil
}

type Alert struct {
	AlertID    int32          `json:"alert_id"`
	VehicleID  sql.NullInt32  `json:"vehicle_id"`
	AlertType  string         `json:"alert_type"`
	Message    sql.NullString `json:"message"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	IsResolved sql.NullBool   `json:"is_resolved"`
}

type Assignment struct {
	AssignmentID int32        `json:"assignment_id"`
	VehicleID    int32        `json:"vehicle_id"`
	DriverID     int32        `json:"driver_id"`
	AssignedFrom time.Time    `json:"assigned_from"`
	AssignedTo   sql.NullTime `json:"assigned_to"`
}

type Cargo struct {
	CargoID     int32              `json:"cargo_id"`
	OrderID     int32              `json:"order_id"`
	Description sql.NullString     `json:"description"`
	WeightKg    sql.NullString     `json:"weight_kg"`
	VolumeM3    sql.NullString     `json:"volume_m3"`
	CargoType   NullCargoCargoType `json:"cargo_type"`
}

type Client struct {
	ClientID     int32          `json:"client_id"`
	CompanyName  string         `json:"company_name"`
	Nip          string         `json:"nip"`
	Address      sql.NullString `json:"address"`
	ContactEmail sql.NullString `json:"contact_email"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Driver struct {
	DriverID          int32             `json:"driver_id"`
	UserID            sql.NullInt32     `json:"user_id"`
	FirstName         string            `json:"first_name"`
	LastName          string            `json:"last_name"`
	Pesel             string            `json:"pesel"`
	Phone             sql.NullString    `json:"phone"`
	Email             sql.NullString    `json:"email"`
	Status            NullDriversStatus `json:"status"`
	DeletedAt         sql.NullTime      `json:"deleted_at"`
	CreatedAt         sql.NullTime      `json:"created_at"`
	UpdatedAt         sql.NullTime      `json:"updated_at"`
	LicenseNumber     sql.NullString    `json:"license_number"`
	LicenseExpiryDate sql.NullTime      `json:"license_expiry_date"`
	AdrCertified      bool              `json:"adr_certified"`
	AdrExpiryDate     sql.NullTime      `json:"adr_expiry_date"`
}

type Order struct {
	OrderID          int32            `json:"order_id"`
	ClientID         int32            `json:"client_id"`
	OrderNumber      string           `json:"order_number"`
	CreationDate     sql.NullTime     `json:"creation_date"`
	DeliveryDeadline sql.NullTime     `json:"delivery_deadline"`
	TotalPricePln    sql.NullString   `json:"total_price_pln"`
	Status           NullOrdersStatus `json:"status"`
}

type Role struct {
	RoleID      int32          `json:"role_id"`
	RoleName    string         `json:"role_name"`
	Description sql.NullString `json:"description"`
}

type Trip struct {
	TripID           int32           `json:"trip_id"`
	OrderID          int32           `json:"order_id"`
	VehicleID        int32           `json:"vehicle_id"`
	DriverID         int32           `json:"driver_id"`
	StartTime        sql.NullTime    `json:"start_time"`
	EndTime          sql.NullTime    `json:"end_time"`
	ActualDistanceKm sql.NullInt32   `json:"actual_distance_km"`
	Status           NullTripsStatus `json:"status"`
}

type User struct {
	UserID              int32         `json:"user_id"`
	RoleID              int32         `json:"role_id"`
	Username            string        `json:"username"`
	PasswordHash        string        `json:"password_hash"`
	Email               string        `json:"email"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	IsActive            sql.NullBool  `json:"is_active"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime  `json:"locked_until"`
}

type Vehicle struct {
	VehicleID        int32              `json:"vehicle_id"`
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	ProductionYear   sql.NullInt16      `json:"production_year"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	DeletedAt        sql.NullTime       `json:"deleted_at"`
	CreatedAt        sql.NullTime       `json:"created_at"`
	UpdatedAt        sql.NullTime       `json:"updated_at"`
}
