// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Role struct {
	RoleID      int32          `json:"role_id"`
	RoleName    string         `json:"role_name"`
	Description sql.NullString `json:"description"`
}

type User struct {
	UserID              int32         `json:"user_id"`
	RoleID              int32         `json:"role_id"`
	Username            string        `json:"username"`
	PasswordHash        string        `json:"password_hash"`
	Email               string        `json:"email"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	IsActive            sql.NullBool  `json:"is_active"`
	FailedLoginAttempts sql.NullInt32 `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime  `json:"locked_until"`
}
