// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :execlastid
INSERT INTO Notification (user_id, ` + "`" + `type` + "`" + `, message, is_read)
VALUES (?, ?, ?, 0)
`

type CreateNotificationParams struct {
	UserID  int32            `json:"user_id"`
	Type    NotificationType `json:"type"`
	Message sql.NullString   `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotification, arg.UserID, arg.Type, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listNotificationForUser = `-- name: ListNotificationForUser :many
SELECT
  id,
  user_id,
  ` + "`" + `type` + "`" + `,
  message,
  is_read,
  created_at
FROM Notification
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListNotificationForUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListNotificationForUserRow struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	Type      NotificationType `json:"type"`
	Message   sql.NullString   `json:"message"`
	IsRead    sql.NullBool     `json:"is_read"`
	CreatedAt sql.NullTime     `json:"created_at"`
}

func (q *Queries) ListNotificationForUser(ctx context.Context, arg ListNotificationForUserParams) ([]ListNotificationForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationForUserRow
	for rows.Next() {
		var i ListNotificationForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationReadForUser = `-- name: MarkNotificationReadForUser :execrows
UPDATE Notification
SET is_read = 1
WHERE id = ?
  AND user_id = ?
`

type MarkNotificationReadForUserParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkNotificationReadForUser(ctx context.Context, arg MarkNotificationReadForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationReadForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
