// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createNotification = `-- name: CreateNotification :execlastid
INSERT INTO notifications (user_id, ` + "`" + `type` + "`" + `, message, is_read)
VALUES (?, ?, ?, 0)
`

type CreateNotificationParams struct {
	UserID  int32             `json:"user_id"`
	Type    NotificationsType `json:"type"`
	Message sql.NullString    `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotification, arg.UserID, arg.Type, arg.Message)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}
