// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_scheduler.sql

package sqlc

import (
	"context"
)

const listSchedulerDriverAdrExpiryNotifications = `-- name: ListSchedulerDriverAdrExpiryNotifications :many
SELECT
  CONCAT('ADR certificate for ', d.first_name, ' ', d.last_name, ' expires on ', DATE_FORMAT(d.adr_expiry_date, '%Y-%m-%d')) AS message
FROM Drivers d
WHERE d.deleted_at IS NULL
  AND d.adr_certified = 1
  AND d.adr_expiry_date IS NOT NULL
  AND d.adr_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL CAST(? AS SIGNED) DAY)
ORDER BY d.adr_expiry_date ASC
LIMIT 50
`

func (q *Queries) ListSchedulerDriverAdrExpiryNotifications(ctx context.Context, dollar_1 int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerDriverAdrExpiryNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerDriverLicenseExpiryNotifications = `-- name: ListSchedulerDriverLicenseExpiryNotifications :many
SELECT
  CONCAT('Driver license for ', d.first_name, ' ', d.last_name, ' expires on ', DATE_FORMAT(d.license_expiry_date, '%Y-%m-%d')) AS message
FROM Drivers d
WHERE d.deleted_at IS NULL
  AND d.license_expiry_date IS NOT NULL
  AND d.license_expiry_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL CAST(? AS SIGNED) DAY)
ORDER BY d.license_expiry_date ASC
LIMIT 50
`

func (q *Queries) ListSchedulerDriverLicenseExpiryNotifications(ctx context.Context, dollar_1 int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerDriverLicenseExpiryNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerInspectionNotifications = `-- name: ListSchedulerInspectionNotifications :many
SELECT
  CONCAT('Vehicle inspection for VIN ', v.vin, ' scheduled on ', DATE_FORMAT(v.next_inspection_date, '%Y-%m-%d')) AS message
FROM Vehicles v
WHERE v.next_inspection_date IS NOT NULL
  AND v.next_inspection_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL CAST(? AS SIGNED) DAY)
  AND v.deleted_at IS NULL
ORDER BY v.next_inspection_date ASC
LIMIT 50
`

func (q *Queries) ListSchedulerInspectionNotifications(ctx context.Context, dollar_1 int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerInspectionNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerInsuranceNotifications = `-- name: ListSchedulerInsuranceNotifications :many
SELECT
  CONCAT('Vehicle insurance policy for VIN ', v.vin, ' expires on ', DATE_FORMAT(ip.end_date, '%Y-%m-%d')) AS message
FROM insurance_policies ip
JOIN Vehicles v ON v.vehicle_id = ip.vehicle_id
WHERE ip.end_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL CAST(? AS SIGNED) DAY)
  AND v.deleted_at IS NULL
ORDER BY ip.end_date ASC
LIMIT 50
`

func (q *Queries) ListSchedulerInsuranceNotifications(ctx context.Context, dollar_1 int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerInsuranceNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerMaintenanceDueNotifications = `-- name: ListSchedulerMaintenanceDueNotifications :many
SELECT
  CONCAT(
    'Scheduled ',
    m.type,
    ' maintenance for VIN ',
    v.vin,
    ' on ',
    DATE_FORMAT(m.start_date, '%Y-%m-%d')
  ) AS message
FROM Maintenance m
JOIN Vehicles v ON v.vehicle_id = m.vehicle_id
WHERE m.status = 'Scheduled'
  AND v.deleted_at IS NULL
  AND m.start_date IS NOT NULL
  AND DATE(m.start_date) BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL CAST(? AS SIGNED) DAY)
ORDER BY m.start_date ASC
LIMIT 50
`

func (q *Queries) ListSchedulerMaintenanceDueNotifications(ctx context.Context, dollar_1 int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulerMaintenanceDueNotifications, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var message string
		if err := rows.Scan(&message); err != nil {
			return nil, err
		}
		items = append(items, message)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
