// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelOrderByID = `-- name: CancelOrderByID :execrows
UPDATE Orders
SET status = 'Cancelled'
WHERE order_id = ?
  AND status NOT IN ('Completed', 'Cancelled')
`

func (q *Queries) CancelOrderByID(ctx context.Context, orderID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelOrderByID, orderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM Orders o
JOIN Clients c ON c.client_id = o.client_id AND c.deleted_at IS NULL
WHERE (? = '' OR o.status = ?)
  AND (
    ? = ''
    OR LOWER(c.company_name) LIKE CONCAT('%', LOWER(?), '%')
    OR c.nip LIKE CONCAT('%', ?, '%')
  )
`

type CountOrdersParams struct {
	Column1 interface{}      `json:"column_1"`
	Status  NullOrdersStatus `json:"status"`
	Column3 interface{}      `json:"column_3"`
	LOWER   string           `json:"LOWER"`
	CONCAT  interface{}      `json:"CONCAT"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrders,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.LOWER,
		arg.CONCAT,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :execlastid
INSERT INTO Orders (client_id, order_number, delivery_deadline, total_price_pln, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	ClientID         int32            `json:"client_id"`
	OrderNumber      string           `json:"order_number"`
	DeliveryDeadline sql.NullTime     `json:"delivery_deadline"`
	TotalPricePln    sql.NullString   `json:"total_price_pln"`
	Status           NullOrdersStatus `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createOrder,
		arg.ClientID,
		arg.OrderNumber,
		arg.DeliveryDeadline,
		arg.TotalPricePln,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const existsOrderWithOrderNumber = `-- name: ExistsOrderWithOrderNumber :one
SELECT EXISTS(
  SELECT 1 FROM Orders WHERE order_number = ? AND order_id <> ?
) AS exists_flag
`

type ExistsOrderWithOrderNumberParams struct {
	OrderNumber string `json:"order_number"`
	OrderID     int32  `json:"order_id"`
}

func (q *Queries) ExistsOrderWithOrderNumber(ctx context.Context, arg ExistsOrderWithOrderNumberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsOrderWithOrderNumber, arg.OrderNumber, arg.OrderID)
	var exists_flag bool
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  o.order_id,
  o.client_id,
  o.order_number,
  o.creation_date,
  o.delivery_deadline,
  o.total_price_pln,
  o.status
FROM Orders o
WHERE o.order_id = ?
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID int32) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.ClientID,
		&i.OrderNumber,
		&i.CreationDate,
		&i.DeliveryDeadline,
		&i.TotalPricePln,
		&i.Status,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT
  o.order_id,
  o.client_id,
  o.order_number,
  o.creation_date,
  o.delivery_deadline,
  o.total_price_pln,
  o.status,
  c.company_name AS client_company_name
FROM Orders o
JOIN Clients c ON c.client_id = o.client_id AND c.deleted_at IS NULL
WHERE (? = '' OR o.status = ?)
  AND (
    ? = ''
    OR LOWER(c.company_name) LIKE CONCAT('%', LOWER(?), '%')
    OR c.nip LIKE CONCAT('%', ?, '%')
  )
ORDER BY o.order_id DESC
LIMIT ? OFFSET ?
`

type ListOrdersParams struct {
	Column1 interface{}      `json:"column_1"`
	Status  NullOrdersStatus `json:"status"`
	Column3 interface{}      `json:"column_3"`
	LOWER   string           `json:"LOWER"`
	CONCAT  interface{}      `json:"CONCAT"`
	Limit   int32            `json:"limit"`
	Offset  int32            `json:"offset"`
}

type ListOrdersRow struct {
	OrderID           int32            `json:"order_id"`
	ClientID          int32            `json:"client_id"`
	OrderNumber       string           `json:"order_number"`
	CreationDate      sql.NullTime     `json:"creation_date"`
	DeliveryDeadline  sql.NullTime     `json:"delivery_deadline"`
	TotalPricePln     sql.NullString   `json:"total_price_pln"`
	Status            NullOrdersStatus `json:"status"`
	ClientCompanyName string           `json:"client_company_name"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrders,
		arg.Column1,
		arg.Status,
		arg.Column3,
		arg.LOWER,
		arg.CONCAT,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersRow
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.OrderID,
			&i.ClientID,
			&i.OrderNumber,
			&i.CreationDate,
			&i.DeliveryDeadline,
			&i.TotalPricePln,
			&i.Status,
			&i.ClientCompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :execrows
UPDATE Orders
SET
  client_id = ?,
  order_number = ?,
  delivery_deadline = ?,
  total_price_pln = ?,
  status = ?
WHERE order_id = ?
`

type UpdateOrderParams struct {
	ClientID         int32            `json:"client_id"`
	OrderNumber      string           `json:"order_number"`
	DeliveryDeadline sql.NullTime     `json:"delivery_deadline"`
	TotalPricePln    sql.NullString   `json:"total_price_pln"`
	Status           NullOrdersStatus `json:"status"`
	OrderID          int32            `json:"order_id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrder,
		arg.ClientID,
		arg.OrderNumber,
		arg.DeliveryDeadline,
		arg.TotalPricePln,
		arg.Status,
		arg.OrderID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
