// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetUserByLogin(ctx context.Context, username string) (GetUserByLoginRow, error)
	UnlockUserAccount(ctx context.Context, userID int32) (int64, error)
	UpdateUserLoginState(ctx context.Context, arg UpdateUserLoginStateParams) error
}

var _ Querier = (*Queries)(nil)
