// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountDrivers(ctx context.Context, arg CountDriversParams) (int64, error)
	CountVehicles(ctx context.Context, arg CountVehiclesParams) (int64, error)
	CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (int64, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (int64, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (int64, error)
	GetActiveAssignmentVehicleID(ctx context.Context, driverID int32) (int32, error)
	GetAdminUserByID(ctx context.Context, userID int32) (GetAdminUserByIDRow, error)
	GetDeletedDriverPESELByID(ctx context.Context, driverID int32) (string, error)
	GetDeletedVehicleVINByID(ctx context.Context, vehicleID int32) (string, error)
	GetDriverByID(ctx context.Context, driverID int32) (GetDriverByIDRow, error)
	GetDriverTripOnDate(ctx context.Context, arg GetDriverTripOnDateParams) (string, error)
	GetRoleIDByName(ctx context.Context, roleName string) (int32, error)
	GetUserByLogin(ctx context.Context, username string) (GetUserByLoginRow, error)
	GetVehicleByID(ctx context.Context, vehicleID int32) (GetVehicleByIDRow, error)
	HasActiveDriverWithPESELExcludingID(ctx context.Context, arg HasActiveDriverWithPESELExcludingIDParams) (bool, error)
	HasActiveTripsByDriverID(ctx context.Context, driverID int32) (bool, error)
	HasActiveTripsByVehicleID(ctx context.Context, vehicleID int32) (bool, error)
	HasActiveVehicleWithVINExcludingID(ctx context.Context, arg HasActiveVehicleWithVINExcludingIDParams) (bool, error)
	ListActiveDriverPESELs(ctx context.Context) ([]ListActiveDriverPESELsRow, error)
	ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error)
	ListDrivers(ctx context.Context, arg ListDriversParams) ([]ListDriversRow, error)
	ListDriversForPESELSearch(ctx context.Context, arg ListDriversForPESELSearchParams) ([]ListDriversForPESELSearchRow, error)
	ListDriversWithExpiringCertificates(ctx context.Context) ([]ListDriversWithExpiringCertificatesRow, error)
	ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error)
	OrderHasHazardousCargo(ctx context.Context, orderID int32) (bool, error)
	RestoreDriverByID(ctx context.Context, driverID int32) (int64, error)
	RestoreVehicleByID(ctx context.Context, vehicleID int32) (int64, error)
	SoftDeleteAdminUser(ctx context.Context, userID int32) (int64, error)
	SoftDeleteDriver(ctx context.Context, driverID int32) (int64, error)
	SoftDeleteVehicle(ctx context.Context, vehicleID int32) (int64, error)
	UnlockUserAccount(ctx context.Context, userID int32) (int64, error)
	UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) (int64, error)
	UpdateDriver(ctx context.Context, arg UpdateDriverParams) (int64, error)
	UpdateUserLoginState(ctx context.Context, arg UpdateUserLoginStateParams) error
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (int64, error)
	UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
