// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getDriverMileageReport = `-- name: GetDriverMileageReport :one
SELECT
  COALESCE(SUM(COALESCE(t.actual_distance_km, CAST(r.planned_distance_km AS DECIMAL(10, 2)))), 0) AS total_km,
  COUNT(DISTINCT t.order_id) AS orders_count
FROM Trips t
LEFT JOIN (
  SELECT order_id, MAX(planned_distance_km) AS planned_distance_km
  FROM Routes
  GROUP BY order_id
) r ON r.order_id = t.order_id
WHERE t.driver_id = ?
  AND t.status = 'Finished'
  AND t.end_time IS NOT NULL
  AND DATE(t.end_time) >= ?
  AND DATE(t.end_time) <= ?
  AND EXISTS (
    SELECT 1
    FROM Assignments a
    WHERE a.driver_id = t.driver_id
      AND a.vehicle_id = t.vehicle_id
      AND a.assigned_from <= COALESCE(t.end_time, t.start_time)
      AND (a.assigned_to IS NULL OR a.assigned_to >= COALESCE(t.start_time, t.end_time))
  )
`

type GetDriverMileageReportParams struct {
	DriverID  int32        `json:"driver_id"`
	EndTime   sql.NullTime `json:"end_time"`
	EndTime_2 sql.NullTime `json:"end_time_2"`
}

type GetDriverMileageReportRow struct {
	TotalKm     interface{} `json:"total_km"`
	OrdersCount int64       `json:"orders_count"`
}

func (q *Queries) GetDriverMileageReport(ctx context.Context, arg GetDriverMileageReportParams) (GetDriverMileageReportRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverMileageReport, arg.DriverID, arg.EndTime, arg.EndTime_2)
	var i GetDriverMileageReportRow
	err := row.Scan(&i.TotalKm, &i.OrdersCount)
	return i, err
}

const getVehicleFuelCostsForMonth = `-- name: GetVehicleFuelCostsForMonth :one
SELECT COALESCE(SUM(fl.total_cost), 0) AS fuel_cost
FROM fuel_logs fl
WHERE fl.vehicle_id = ?
  AND DATE_FORMAT(fl.date, '%Y-%m') = ?
`

type GetVehicleFuelCostsForMonthParams struct {
	VehicleID int32     `json:"vehicle_id"`
	Date      time.Time `json:"date"`
}

func (q *Queries) GetVehicleFuelCostsForMonth(ctx context.Context, arg GetVehicleFuelCostsForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleFuelCostsForMonth, arg.VehicleID, arg.Date)
	var fuel_cost interface{}
	err := row.Scan(&fuel_cost)
	return fuel_cost, err
}

const getVehicleInsuranceMonthlyCost = `-- name: GetVehicleInsuranceMonthlyCost :one
SELECT COALESCE(SUM(ip.cost / 12), 0) AS insurance_cost
FROM insurance_policies ip
WHERE ip.vehicle_id = ?
  AND ip.start_date <= ?
  AND ip.end_date >= ?
`

type GetVehicleInsuranceMonthlyCostParams struct {
	VehicleID int32     `json:"vehicle_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetVehicleInsuranceMonthlyCost(ctx context.Context, arg GetVehicleInsuranceMonthlyCostParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleInsuranceMonthlyCost, arg.VehicleID, arg.StartDate, arg.EndDate)
	var insurance_cost interface{}
	err := row.Scan(&insurance_cost)
	return insurance_cost, err
}

const getVehicleMaintenanceCostsForMonth = `-- name: GetVehicleMaintenanceCostsForMonth :one
SELECT COALESCE(SUM(m.total_cost_pln), 0) AS maintenance_cost
FROM Maintenance m
WHERE m.vehicle_id = ?
  AND m.start_date IS NOT NULL
  AND DATE_FORMAT(m.start_date, '%Y-%m') = ?
`

type GetVehicleMaintenanceCostsForMonthParams struct {
	VehicleID int32        `json:"vehicle_id"`
	StartDate sql.NullTime `json:"start_date"`
}

func (q *Queries) GetVehicleMaintenanceCostsForMonth(ctx context.Context, arg GetVehicleMaintenanceCostsForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleMaintenanceCostsForMonth, arg.VehicleID, arg.StartDate)
	var maintenance_cost interface{}
	err := row.Scan(&maintenance_cost)
	return maintenance_cost, err
}

const getVehicleRevenueForMonth = `-- name: GetVehicleRevenueForMonth :one
SELECT COALESCE(SUM(o.total_price_pln), 0) AS revenue
FROM Orders o
WHERE o.order_id IN (
  SELECT DISTINCT t.order_id
  FROM Trips t
  WHERE t.vehicle_id = ?
)
  AND DATE_FORMAT(o.creation_date, '%Y-%m') = ?
`

type GetVehicleRevenueForMonthParams struct {
	VehicleID    int32        `json:"vehicle_id"`
	CreationDate sql.NullTime `json:"creation_date"`
}

func (q *Queries) GetVehicleRevenueForMonth(ctx context.Context, arg GetVehicleRevenueForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleRevenueForMonth, arg.VehicleID, arg.CreationDate)
	var revenue interface{}
	err := row.Scan(&revenue)
	return revenue, err
}

const getVehicleTollsForMonth = `-- name: GetVehicleTollsForMonth :one
SELECT COALESCE(SUM(c.amount), 0) AS tolls_cost
FROM costs c
WHERE c.vehicle_id = ?
  AND c.category = 'Tolls'
  AND DATE_FORMAT(c.date, '%Y-%m') = ?
`

type GetVehicleTollsForMonthParams struct {
	VehicleID int32     `json:"vehicle_id"`
	Date      time.Time `json:"date"`
}

func (q *Queries) GetVehicleTollsForMonth(ctx context.Context, arg GetVehicleTollsForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleTollsForMonth, arg.VehicleID, arg.Date)
	var tolls_cost interface{}
	err := row.Scan(&tolls_cost)
	return tolls_cost, err
}
