// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getDriverMileageReport = `-- name: GetDriverMileageReport :one
SELECT
  COALESCE(SUM(COALESCE(t.actual_distance_km, CAST(r.planned_distance_km AS DECIMAL(10, 2)))), 0) AS total_km,
  COUNT(DISTINCT t.order_id) AS orders_count
FROM Trips t
LEFT JOIN (
  SELECT order_id, MAX(planned_distance_km) AS planned_distance_km
  FROM Routes
  GROUP BY order_id
) r ON r.order_id = t.order_id
WHERE t.driver_id = ?
  AND t.status = 'Finished'
  AND t.end_time IS NOT NULL
  AND DATE(t.end_time) >= ?
  AND DATE(t.end_time) <= ?
`

type GetDriverMileageReportParams struct {
	DriverID  int32        `json:"driver_id"`
	EndTime   sql.NullTime `json:"end_time"`
	EndTime_2 sql.NullTime `json:"end_time_2"`
}

type GetDriverMileageReportRow struct {
	TotalKm     interface{} `json:"total_km"`
	OrdersCount int64       `json:"orders_count"`
}

func (q *Queries) GetDriverMileageReport(ctx context.Context, arg GetDriverMileageReportParams) (GetDriverMileageReportRow, error) {
	row := q.db.QueryRowContext(ctx, getDriverMileageReport, arg.DriverID, arg.EndTime, arg.EndTime_2)
	var i GetDriverMileageReportRow
	err := row.Scan(&i.TotalKm, &i.OrdersCount)
	return i, err
}

const getGlobalFuelCostInRange = `-- name: GetGlobalFuelCostInRange :one
SELECT COALESCE(SUM(fl.total_cost), 0) AS total
FROM FuelLog fl
WHERE fl.date >= ?
  AND fl.date <= ?
`

type GetGlobalFuelCostInRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetGlobalFuelCostInRange(ctx context.Context, arg GetGlobalFuelCostInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getGlobalFuelCostInRange, arg.Date, arg.Date_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getGlobalInsuranceCostInRange = `-- name: GetGlobalInsuranceCostInRange :one
SELECT COALESCE(SUM(
  ip.cost * (
    DATEDIFF(
      LEAST(ip.end_date, ?),
      GREATEST(ip.start_date, ?)
    ) + 1
  ) / NULLIF(DATEDIFF(ip.end_date, ip.start_date) + 1, 0)
), 0) AS total
FROM InsurancePolicy ip
WHERE LEAST(ip.end_date, ?) >= GREATEST(ip.start_date, ?)
`

type GetGlobalInsuranceCostInRangeParams struct {
	PeriodEnd   interface{} `json:"period_end"`
	PeriodStart interface{} `json:"period_start"`
}

// Insurance: prorate policy cost by overlap days with the report period.
func (q *Queries) GetGlobalInsuranceCostInRange(ctx context.Context, arg GetGlobalInsuranceCostInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getGlobalInsuranceCostInRange,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.PeriodStart,
	)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getGlobalMaintenanceCostInRange = `-- name: GetGlobalMaintenanceCostInRange :one
SELECT COALESCE(SUM(m.total_cost_pln), 0) AS total
FROM Maintenance m
WHERE m.start_date IS NOT NULL
  AND DATE(m.start_date) >= ?
  AND DATE(m.start_date) <= ?
`

type GetGlobalMaintenanceCostInRangeParams struct {
	StartDate   sql.NullTime `json:"start_date"`
	StartDate_2 sql.NullTime `json:"start_date_2"`
}

func (q *Queries) GetGlobalMaintenanceCostInRange(ctx context.Context, arg GetGlobalMaintenanceCostInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getGlobalMaintenanceCostInRange, arg.StartDate, arg.StartDate_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getGlobalOtherCostInRange = `-- name: GetGlobalOtherCostInRange :one
SELECT COALESCE(SUM(c.amount), 0) AS total
FROM Cost c
WHERE c.category = 'Other'
  AND c.date >= ?
  AND c.date <= ?
`

type GetGlobalOtherCostInRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetGlobalOtherCostInRange(ctx context.Context, arg GetGlobalOtherCostInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getGlobalOtherCostInRange, arg.Date, arg.Date_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getGlobalTollsCostInRange = `-- name: GetGlobalTollsCostInRange :one
SELECT COALESCE(SUM(c.amount), 0) AS total
FROM Cost c
WHERE c.category = 'Tolls'
  AND c.date >= ?
  AND c.date <= ?
`

type GetGlobalTollsCostInRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetGlobalTollsCostInRange(ctx context.Context, arg GetGlobalTollsCostInRangeParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getGlobalTollsCostInRange, arg.Date, arg.Date_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const getVehicleFuelCostForMonth = `-- name: GetVehicleFuelCostForMonth :one
SELECT COALESCE(SUM(fl.total_cost), 0) AS fuel_cost
FROM FuelLog fl
WHERE fl.vehicle_id = ?
  AND fl.date >= ?
  AND fl.date < ?
`

type GetVehicleFuelCostForMonthParams struct {
	VehicleID int32     `json:"vehicle_id"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

func (q *Queries) GetVehicleFuelCostForMonth(ctx context.Context, arg GetVehicleFuelCostForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleFuelCostForMonth, arg.VehicleID, arg.Date, arg.Date_2)
	var fuel_cost interface{}
	err := row.Scan(&fuel_cost)
	return fuel_cost, err
}

const getVehicleInsuranceMonthlyCost = `-- name: GetVehicleInsuranceMonthlyCost :one
SELECT COALESCE(SUM(ip.cost / 12), 0) AS insurance_cost
FROM InsurancePolicy ip
WHERE ip.vehicle_id = ?
  AND ip.start_date <= ?
  AND ip.end_date >= ?
`

type GetVehicleInsuranceMonthlyCostParams struct {
	VehicleID int32     `json:"vehicle_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetVehicleInsuranceMonthlyCost(ctx context.Context, arg GetVehicleInsuranceMonthlyCostParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleInsuranceMonthlyCost, arg.VehicleID, arg.StartDate, arg.EndDate)
	var insurance_cost interface{}
	err := row.Scan(&insurance_cost)
	return insurance_cost, err
}

const getVehicleMaintenanceCostForMonth = `-- name: GetVehicleMaintenanceCostForMonth :one
SELECT COALESCE(SUM(m.total_cost_pln), 0) AS maintenance_cost
FROM Maintenance m
WHERE m.vehicle_id = ?
  AND m.start_date IS NOT NULL
  AND m.start_date >= ?
  AND m.start_date < ?
`

type GetVehicleMaintenanceCostForMonthParams struct {
	VehicleID   int32        `json:"vehicle_id"`
	StartDate   sql.NullTime `json:"start_date"`
	StartDate_2 sql.NullTime `json:"start_date_2"`
}

func (q *Queries) GetVehicleMaintenanceCostForMonth(ctx context.Context, arg GetVehicleMaintenanceCostForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleMaintenanceCostForMonth, arg.VehicleID, arg.StartDate, arg.StartDate_2)
	var maintenance_cost interface{}
	err := row.Scan(&maintenance_cost)
	return maintenance_cost, err
}

const getVehicleRevenueForMonth = `-- name: GetVehicleRevenueForMonth :one
SELECT COALESCE(SUM(o.total_price_pln), 0) AS revenue
FROM Orders o
WHERE o.order_id IN (
  SELECT DISTINCT t.order_id
  FROM Trips t
  WHERE t.vehicle_id = ?
    AND COALESCE(t.end_time, t.start_time) >= ?
    AND COALESCE(t.end_time, t.start_time) < ?
)
`

type GetVehicleRevenueForMonthParams struct {
	VehicleID int32        `json:"vehicle_id"`
	EndTime   sql.NullTime `json:"end_time"`
	EndTime_2 sql.NullTime `json:"end_time_2"`
}

func (q *Queries) GetVehicleRevenueForMonth(ctx context.Context, arg GetVehicleRevenueForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleRevenueForMonth, arg.VehicleID, arg.EndTime, arg.EndTime_2)
	var revenue interface{}
	err := row.Scan(&revenue)
	return revenue, err
}

const getVehicleTollsForMonth = `-- name: GetVehicleTollsForMonth :one
SELECT COALESCE(SUM(c.amount), 0) AS tolls_cost
FROM Cost c
WHERE c.vehicle_id = ?
  AND c.category = 'Tolls'
  AND c.date >= ?
  AND c.date < ?
`

type GetVehicleTollsForMonthParams struct {
	VehicleID int32     `json:"vehicle_id"`
	Date      time.Time `json:"date"`
	Date_2    time.Time `json:"date_2"`
}

func (q *Queries) GetVehicleTollsForMonth(ctx context.Context, arg GetVehicleTollsForMonthParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVehicleTollsForMonth, arg.VehicleID, arg.Date, arg.Date_2)
	var tolls_cost interface{}
	err := row.Scan(&tolls_cost)
	return tolls_cost, err
}
