// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package sqlc

import (
	"context"
)

const countActiveTripsForOrder = `-- name: CountActiveTripsForOrder :one
SELECT COUNT(*)
FROM Trips
WHERE order_id = ?
  AND status IN ('Scheduled', 'Active')
`

func (q *Queries) CountActiveTripsForOrder(ctx context.Context, orderID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTripsForOrder, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT route_id, order_id, start_location, end_location, planned_distance_km, estimated_time_min
FROM Routes
WHERE route_id = ?
LIMIT 1
`

func (q *Queries) GetRouteByID(ctx context.Context, routeID int32) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteByID, routeID)
	var i Route
	err := row.Scan(
		&i.RouteID,
		&i.OrderID,
		&i.StartLocation,
		&i.EndLocation,
		&i.PlannedDistanceKm,
		&i.EstimatedTimeMin,
	)
	return i, err
}
