// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTrip = `-- name: CreateTrip :execlastid
INSERT INTO Trips (order_id, vehicle_id, driver_id, start_time, status)
VALUES (?, ?, ?, ?, ?)
`

type CreateTripParams struct {
	OrderID   int32           `json:"order_id"`
	VehicleID int32           `json:"vehicle_id"`
	DriverID  int32           `json:"driver_id"`
	StartTime sql.NullTime    `json:"start_time"`
	Status    NullTripsStatus `json:"status"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTrip,
		arg.OrderID,
		arg.VehicleID,
		arg.DriverID,
		arg.StartTime,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getTripByID = `-- name: GetTripByID :one
SELECT
  t.trip_id,
  t.order_id,
  o.order_number,
  c.company_name AS client_company,
  t.vehicle_id,
  v.vin AS vehicle_vin,
  t.driver_id,
  d.first_name,
  d.last_name,
  r.planned_distance_km,
  t.start_time,
  t.end_time,
  t.actual_distance_km,
  t.status
FROM Trips t
JOIN Orders o ON o.order_id = t.order_id
JOIN Clients c ON c.client_id = o.client_id
JOIN Vehicles v ON v.vehicle_id = t.vehicle_id
JOIN Drivers d ON d.driver_id = t.driver_id
LEFT JOIN Routes r ON r.order_id = o.order_id
WHERE t.trip_id = ?
LIMIT 1
`

type GetTripByIDRow struct {
	TripID            int32           `json:"trip_id"`
	OrderID           int32           `json:"order_id"`
	OrderNumber       string          `json:"order_number"`
	ClientCompany     string          `json:"client_company"`
	VehicleID         int32           `json:"vehicle_id"`
	VehicleVin        string          `json:"vehicle_vin"`
	DriverID          int32           `json:"driver_id"`
	FirstName         string          `json:"first_name"`
	LastName          string          `json:"last_name"`
	PlannedDistanceKm sql.NullString  `json:"planned_distance_km"`
	StartTime         sql.NullTime    `json:"start_time"`
	EndTime           sql.NullTime    `json:"end_time"`
	ActualDistanceKm  sql.NullInt32   `json:"actual_distance_km"`
	Status            NullTripsStatus `json:"status"`
}

func (q *Queries) GetTripByID(ctx context.Context, tripID int32) (GetTripByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTripByID, tripID)
	var i GetTripByIDRow
	err := row.Scan(
		&i.TripID,
		&i.OrderID,
		&i.OrderNumber,
		&i.ClientCompany,
		&i.VehicleID,
		&i.VehicleVin,
		&i.DriverID,
		&i.FirstName,
		&i.LastName,
		&i.PlannedDistanceKm,
		&i.StartTime,
		&i.EndTime,
		&i.ActualDistanceKm,
		&i.Status,
	)
	return i, err
}

const getTripOrderVehicleDriverIDs = `-- name: GetTripOrderVehicleDriverIDs :one
SELECT order_id, vehicle_id, driver_id
FROM Trips
WHERE trip_id = ?
LIMIT 1
`

type GetTripOrderVehicleDriverIDsRow struct {
	OrderID   int32 `json:"order_id"`
	VehicleID int32 `json:"vehicle_id"`
	DriverID  int32 `json:"driver_id"`
}

func (q *Queries) GetTripOrderVehicleDriverIDs(ctx context.Context, tripID int32) (GetTripOrderVehicleDriverIDsRow, error) {
	row := q.db.QueryRowContext(ctx, getTripOrderVehicleDriverIDs, tripID)
	var i GetTripOrderVehicleDriverIDsRow
	err := row.Scan(&i.OrderID, &i.VehicleID, &i.DriverID)
	return i, err
}

const getTripStatusByID = `-- name: GetTripStatusByID :one
SELECT status
FROM Trips
WHERE trip_id = ?
LIMIT 1
`

func (q *Queries) GetTripStatusByID(ctx context.Context, tripID int32) (NullTripsStatus, error) {
	row := q.db.QueryRowContext(ctx, getTripStatusByID, tripID)
	var status NullTripsStatus
	err := row.Scan(&status)
	return status, err
}

const listTrips = `-- name: ListTrips :many
SELECT
  t.trip_id,
  t.order_id,
  o.order_number,
  c.company_name AS client_company,
  t.vehicle_id,
  v.vin AS vehicle_vin,
  t.driver_id,
  d.first_name,
  d.last_name,
  r.planned_distance_km,
  t.start_time,
  t.end_time,
  t.actual_distance_km,
  t.status
FROM Trips t
JOIN Orders o ON o.order_id = t.order_id
JOIN Clients c ON c.client_id = o.client_id
JOIN Vehicles v ON v.vehicle_id = t.vehicle_id
JOIN Drivers d ON d.driver_id = t.driver_id
LEFT JOIN Routes r ON r.order_id = o.order_id
WHERE (? = '' OR t.status = ?)
ORDER BY t.trip_id DESC
`

type ListTripsParams struct {
	Column1 interface{}     `json:"column_1"`
	Status  NullTripsStatus `json:"status"`
}

type ListTripsRow struct {
	TripID            int32           `json:"trip_id"`
	OrderID           int32           `json:"order_id"`
	OrderNumber       string          `json:"order_number"`
	ClientCompany     string          `json:"client_company"`
	VehicleID         int32           `json:"vehicle_id"`
	VehicleVin        string          `json:"vehicle_vin"`
	DriverID          int32           `json:"driver_id"`
	FirstName         string          `json:"first_name"`
	LastName          string          `json:"last_name"`
	PlannedDistanceKm sql.NullString  `json:"planned_distance_km"`
	StartTime         sql.NullTime    `json:"start_time"`
	EndTime           sql.NullTime    `json:"end_time"`
	ActualDistanceKm  sql.NullInt32   `json:"actual_distance_km"`
	Status            NullTripsStatus `json:"status"`
}

func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]ListTripsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrips, arg.Column1, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsRow
	for rows.Next() {
		var i ListTripsRow
		if err := rows.Scan(
			&i.TripID,
			&i.OrderID,
			&i.OrderNumber,
			&i.ClientCompany,
			&i.VehicleID,
			&i.VehicleVin,
			&i.DriverID,
			&i.FirstName,
			&i.LastName,
			&i.PlannedDistanceKm,
			&i.StartTime,
			&i.EndTime,
			&i.ActualDistanceKm,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByOrderID = `-- name: ListTripsByOrderID :many
SELECT
  t.trip_id,
  t.order_id,
  o.order_number,
  c.company_name AS client_company,
  t.vehicle_id,
  v.vin AS vehicle_vin,
  t.driver_id,
  d.first_name,
  d.last_name,
  r.planned_distance_km,
  t.start_time,
  t.end_time,
  t.actual_distance_km,
  t.status
FROM Trips t
JOIN Orders o ON o.order_id = t.order_id
JOIN Clients c ON c.client_id = o.client_id
JOIN Vehicles v ON v.vehicle_id = t.vehicle_id
JOIN Drivers d ON d.driver_id = t.driver_id
LEFT JOIN Routes r ON r.order_id = o.order_id
WHERE t.order_id = ?
ORDER BY t.trip_id DESC
`

type ListTripsByOrderIDRow struct {
	TripID            int32           `json:"trip_id"`
	OrderID           int32           `json:"order_id"`
	OrderNumber       string          `json:"order_number"`
	ClientCompany     string          `json:"client_company"`
	VehicleID         int32           `json:"vehicle_id"`
	VehicleVin        string          `json:"vehicle_vin"`
	DriverID          int32           `json:"driver_id"`
	FirstName         string          `json:"first_name"`
	LastName          string          `json:"last_name"`
	PlannedDistanceKm sql.NullString  `json:"planned_distance_km"`
	StartTime         sql.NullTime    `json:"start_time"`
	EndTime           sql.NullTime    `json:"end_time"`
	ActualDistanceKm  sql.NullInt32   `json:"actual_distance_km"`
	Status            NullTripsStatus `json:"status"`
}

func (q *Queries) ListTripsByOrderID(ctx context.Context, orderID int32) ([]ListTripsByOrderIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTripsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsByOrderIDRow
	for rows.Next() {
		var i ListTripsByOrderIDRow
		if err := rows.Scan(
			&i.TripID,
			&i.OrderID,
			&i.OrderNumber,
			&i.ClientCompany,
			&i.VehicleID,
			&i.VehicleVin,
			&i.DriverID,
			&i.FirstName,
			&i.LastName,
			&i.PlannedDistanceKm,
			&i.StartTime,
			&i.EndTime,
			&i.ActualDistanceKm,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverStatusByID = `-- name: UpdateDriverStatusByID :execrows
UPDATE Drivers
SET status = ?, updated_at = NOW()
WHERE driver_id = ?
  AND deleted_at IS NULL
`

type UpdateDriverStatusByIDParams struct {
	Status   NullDriversStatus `json:"status"`
	DriverID int32             `json:"driver_id"`
}

func (q *Queries) UpdateDriverStatusByID(ctx context.Context, arg UpdateDriverStatusByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDriverStatusByID, arg.Status, arg.DriverID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOrderStatusByID = `-- name: UpdateOrderStatusByID :execrows
UPDATE Orders
SET status = ?
WHERE order_id = ?
`

type UpdateOrderStatusByIDParams struct {
	Status  NullOrdersStatus `json:"status"`
	OrderID int32            `json:"order_id"`
}

func (q *Queries) UpdateOrderStatusByID(ctx context.Context, arg UpdateOrderStatusByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateOrderStatusByID, arg.Status, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTripStatusAbort = `-- name: UpdateTripStatusAbort :execrows
UPDATE Trips
SET end_time = NOW(), status = 'Aborted'
WHERE trip_id = ?
  AND status IN ('Scheduled', 'Active')
`

func (q *Queries) UpdateTripStatusAbort(ctx context.Context, tripID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTripStatusAbort, tripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTripStatusFinish = `-- name: UpdateTripStatusFinish :execrows
UPDATE Trips
SET end_time = NOW(), actual_distance_km = ?, status = 'Finished'
WHERE trip_id = ?
  AND status = 'Active'
`

type UpdateTripStatusFinishParams struct {
	ActualDistanceKm sql.NullInt32 `json:"actual_distance_km"`
	TripID           int32         `json:"trip_id"`
}

func (q *Queries) UpdateTripStatusFinish(ctx context.Context, arg UpdateTripStatusFinishParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTripStatusFinish, arg.ActualDistanceKm, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTripStatusStart = `-- name: UpdateTripStatusStart :execrows
UPDATE Trips
SET start_time = NOW(), status = 'Active'
WHERE trip_id = ?
  AND status = 'Scheduled'
`

func (q *Queries) UpdateTripStatusStart(ctx context.Context, tripID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTripStatusStart, tripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVehicleStatusByID = `-- name: UpdateVehicleStatusByID :execrows
UPDATE Vehicles
SET status = ?, updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleStatusByIDParams struct {
	Status    NullVehiclesStatus `json:"status"`
	VehicleID int32              `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicleStatusByID(ctx context.Context, arg UpdateVehicleStatusByIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicleStatusByID, arg.Status, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
