// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createAdminUser = `-- name: CreateAdminUser :execlastid
INSERT INTO Users (
  role_id,
  username,
  password_hash,
  email,
  is_active,
  failed_login_attempts,
  locked_until
)
VALUES (?, ?, ?, ?, 1, 0, NULL)
`

type CreateAdminUserParams struct {
	RoleID       int32  `json:"role_id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Email        string `json:"email"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAdminUser,
		arg.RoleID,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT
  u.user_id,
  u.username,
  u.email,
  r.role_name,
  u.is_active,
  u.created_at
FROM Users u
JOIN Roles r ON r.role_id = u.role_id
WHERE u.user_id = ?
LIMIT 1
`

type GetAdminUserByIDRow struct {
	UserID    int32        `json:"user_id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	RoleName  string       `json:"role_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetAdminUserByID(ctx context.Context, userID int32) (GetAdminUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAdminUserByID, userID)
	var i GetAdminUserByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.RoleName,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleIDByName = `-- name: GetRoleIDByName :one
SELECT role_id
FROM Roles
WHERE role_name = ?
LIMIT 1
`

func (q *Queries) GetRoleIDByName(ctx context.Context, roleName string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRoleIDByName, roleName)
	var role_id int32
	err := row.Scan(&role_id)
	return role_id, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT
  u.user_id,
  u.username,
  u.email,
  r.role_name,
  u.is_active,
  u.created_at
FROM Users u
JOIN Roles r ON r.role_id = u.role_id
ORDER BY u.user_id ASC
`

type ListAdminUsersRow struct {
	UserID    int32        `json:"user_id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	RoleName  string       `json:"role_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) ListAdminUsers(ctx context.Context) ([]ListAdminUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminUsersRow
	for rows.Next() {
		var i ListAdminUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.RoleName,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAdminUser = `-- name: SoftDeleteAdminUser :execrows
UPDATE Users
SET is_active = 0
WHERE user_id = ?
`

func (q *Queries) SoftDeleteAdminUser(ctx context.Context, userID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteAdminUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAdminUser = `-- name: UpdateAdminUser :execrows
UPDATE Users
SET role_id = ?, username = ?, email = ?
WHERE user_id = ?
`

type UpdateAdminUserParams struct {
	RoleID   int32  `json:"role_id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	UserID   int32  `json:"user_id"`
}

func (q *Queries) UpdateAdminUser(ctx context.Context, arg UpdateAdminUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAdminUser,
		arg.RoleID,
		arg.Username,
		arg.Email,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
