// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countVehicles = `-- name: CountVehicles :one
SELECT COUNT(*)
FROM Vehicles
WHERE deleted_at IS NULL
  AND (? = '' OR status = ?)
`

type CountVehiclesParams struct {
	Column1 interface{}        `json:"column_1"`
	Status  NullVehiclesStatus `json:"status"`
}

func (q *Queries) CountVehicles(ctx context.Context, arg CountVehiclesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVehicles, arg.Column1, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicle = `-- name: CreateVehicle :execlastid
INSERT INTO Vehicles (
  vin,
  plate_number,
  brand,
  model,
  capacity_kg,
  current_mileage_km,
  status
)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateVehicleParams struct {
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVehicle,
		arg.Vin,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.CapacityKg,
		arg.CurrentMileageKm,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT
  vehicle_id,
  vin,
  plate_number,
  brand,
  model,
  capacity_kg,
  current_mileage_km,
  status,
  created_at,
  updated_at
FROM Vehicles
WHERE vehicle_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

type GetVehicleByIDRow struct {
	VehicleID        int32              `json:"vehicle_id"`
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	CreatedAt        sql.NullTime       `json:"created_at"`
	UpdatedAt        sql.NullTime       `json:"updated_at"`
}

func (q *Queries) GetVehicleByID(ctx context.Context, vehicleID int32) (GetVehicleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByID, vehicleID)
	var i GetVehicleByIDRow
	err := row.Scan(
		&i.VehicleID,
		&i.Vin,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.CapacityKg,
		&i.CurrentMileageKm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT
  vehicle_id,
  vin,
  plate_number,
  brand,
  model,
  capacity_kg,
  current_mileage_km,
  status,
  created_at,
  updated_at
FROM Vehicles
WHERE deleted_at IS NULL
  AND (? = '' OR status = ?)
ORDER BY vehicle_id DESC
LIMIT ? OFFSET ?
`

type ListVehiclesParams struct {
	Column1 interface{}        `json:"column_1"`
	Status  NullVehiclesStatus `json:"status"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

type ListVehiclesRow struct {
	VehicleID        int32              `json:"vehicle_id"`
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	CreatedAt        sql.NullTime       `json:"created_at"`
	UpdatedAt        sql.NullTime       `json:"updated_at"`
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicles,
		arg.Column1,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehiclesRow
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.VehicleID,
			&i.Vin,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
			&i.CapacityKg,
			&i.CurrentMileageKm,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVehicle = `-- name: SoftDeleteVehicle :execrows
UPDATE Vehicles
SET deleted_at = NOW(), updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVehicle(ctx context.Context, vehicleID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteVehicle, vehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVehicle = `-- name: UpdateVehicle :execrows
UPDATE Vehicles
SET
  vin = ?,
  plate_number = ?,
  brand = ?,
  model = ?,
  capacity_kg = ?,
  current_mileage_km = ?,
  status = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleParams struct {
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	VehicleID        int32              `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicle,
		arg.Vin,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.CapacityKg,
		arg.CurrentMileageKm,
		arg.Status,
		arg.VehicleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVehicleStatus = `-- name: UpdateVehicleStatus :execrows
UPDATE Vehicles
SET
  status = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleStatusParams struct {
	Status    NullVehiclesStatus `json:"status"`
	VehicleID int32              `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicleStatus, arg.Status, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
