// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countVehicles = `-- name: CountVehicles :one
SELECT COUNT(*)
FROM Vehicles
WHERE (? = 1 OR deleted_at IS NULL)
  AND (? = '' OR LOWER(vin) LIKE CONCAT('%', LOWER(?), '%') OR LOWER(brand) LIKE CONCAT('%', LOWER(?), '%'))
  AND (? = '' OR status = ?)
`

type CountVehiclesParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 interface{}        `json:"column_2"`
	LOWER   string             `json:"LOWER"`
	LOWER_2 string             `json:"LOWER_2"`
	Column5 interface{}        `json:"column_5"`
	Status  NullVehiclesStatus `json:"status"`
}

func (q *Queries) CountVehicles(ctx context.Context, arg CountVehiclesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVehicles,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.LOWER_2,
		arg.Column5,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicle = `-- name: CreateVehicle :execlastid
INSERT INTO Vehicles (
  vin,
  plate_number,
  brand,
  model,
  production_year,
  capacity_kg,
  current_mileage_km,
  status
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVehicleParams struct {
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	ProductionYear   sql.NullInt16      `json:"production_year"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createVehicle,
		arg.Vin,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.CapacityKg,
		arg.CurrentMileageKm,
		arg.Status,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getDeletedVehicleVINByID = `-- name: GetDeletedVehicleVINByID :one
SELECT vin
FROM Vehicles
WHERE vehicle_id = ?
  AND deleted_at IS NOT NULL
LIMIT 1
`

func (q *Queries) GetDeletedVehicleVINByID(ctx context.Context, vehicleID int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getDeletedVehicleVINByID, vehicleID)
	var vin string
	err := row.Scan(&vin)
	return vin, err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT
  vehicle_id,
  vin,
  plate_number,
  brand,
  model,
  production_year,
  capacity_kg,
  current_mileage_km,
  status,
  created_at,
  updated_at
FROM Vehicles
WHERE vehicle_id = ?
  AND deleted_at IS NULL
LIMIT 1
`

type GetVehicleByIDRow struct {
	VehicleID        int32              `json:"vehicle_id"`
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	ProductionYear   sql.NullInt16      `json:"production_year"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	CreatedAt        sql.NullTime       `json:"created_at"`
	UpdatedAt        sql.NullTime       `json:"updated_at"`
}

func (q *Queries) GetVehicleByID(ctx context.Context, vehicleID int32) (GetVehicleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleByID, vehicleID)
	var i GetVehicleByIDRow
	err := row.Scan(
		&i.VehicleID,
		&i.Vin,
		&i.PlateNumber,
		&i.Brand,
		&i.Model,
		&i.ProductionYear,
		&i.CapacityKg,
		&i.CurrentMileageKm,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleTripInRange = `-- name: GetVehicleTripInRange :one
SELECT
  trip_id,
  status,
  start_time,
  end_time
FROM Trips
WHERE vehicle_id = ?
  AND status IN ('Scheduled', 'Active')
  AND (
    (start_time BETWEEN ? AND ?)
    OR (end_time IS NOT NULL AND end_time BETWEEN ? AND ?)
    OR (start_time <= ? AND (end_time IS NULL OR end_time >= ?))
  )
ORDER BY start_time
LIMIT 1
`

type GetVehicleTripInRangeParams struct {
	VehicleID     int32        `json:"vehicle_id"`
	FromStartTime sql.NullTime `json:"from_start_time"`
	ToStartTime   sql.NullTime `json:"to_start_time"`
	FromEndTime   sql.NullTime `json:"from_end_time"`
	ToEndTime     sql.NullTime `json:"to_end_time"`
	StartTime     sql.NullTime `json:"start_time"`
	EndTime       sql.NullTime `json:"end_time"`
}

type GetVehicleTripInRangeRow struct {
	TripID    int32           `json:"trip_id"`
	Status    NullTripsStatus `json:"status"`
	StartTime sql.NullTime    `json:"start_time"`
	EndTime   sql.NullTime    `json:"end_time"`
}

func (q *Queries) GetVehicleTripInRange(ctx context.Context, arg GetVehicleTripInRangeParams) (GetVehicleTripInRangeRow, error) {
	row := q.db.QueryRowContext(ctx, getVehicleTripInRange,
		arg.VehicleID,
		arg.FromStartTime,
		arg.ToStartTime,
		arg.FromEndTime,
		arg.ToEndTime,
		arg.StartTime,
		arg.EndTime,
	)
	var i GetVehicleTripInRangeRow
	err := row.Scan(
		&i.TripID,
		&i.Status,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const hasActiveTripsByVehicleID = `-- name: HasActiveTripsByVehicleID :one
SELECT EXISTS(
  SELECT 1
  FROM Trips
  WHERE vehicle_id = ?
    AND status IN ('Active', 'Scheduled')
)
`

func (q *Queries) HasActiveTripsByVehicleID(ctx context.Context, vehicleID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveTripsByVehicleID, vehicleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const hasActiveVehicleWithVINExcludingID = `-- name: HasActiveVehicleWithVINExcludingID :one
SELECT EXISTS(
  SELECT 1
  FROM Vehicles
  WHERE vin = ?
    AND deleted_at IS NULL
    AND vehicle_id <> ?
)
`

type HasActiveVehicleWithVINExcludingIDParams struct {
	Vin       string `json:"vin"`
	VehicleID int32  `json:"vehicle_id"`
}

func (q *Queries) HasActiveVehicleWithVINExcludingID(ctx context.Context, arg HasActiveVehicleWithVINExcludingIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveVehicleWithVINExcludingID, arg.Vin, arg.VehicleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listVehicleMaintenanceHistory = `-- name: ListVehicleMaintenanceHistory :many
SELECT
  maintenance_id,
  type,
  status,
  start_date,
  end_date,
  parts_cost_pln,
  labor_cost_pln,
  total_cost_pln,
  description
FROM Maintenance
WHERE vehicle_id = ?
  AND (? = '' OR type = ?)
  AND (? = '' OR status = ?)
ORDER BY COALESCE(end_date, start_date, created_at) DESC, maintenance_id DESC
`

type ListVehicleMaintenanceHistoryParams struct {
	VehicleID int32             `json:"vehicle_id"`
	Column2   interface{}       `json:"column_2"`
	Type      MaintenanceType   `json:"type"`
	Column4   interface{}       `json:"column_4"`
	Status    MaintenanceStatus `json:"status"`
}

type ListVehicleMaintenanceHistoryRow struct {
	MaintenanceID int32             `json:"maintenance_id"`
	Type          MaintenanceType   `json:"type"`
	Status        MaintenanceStatus `json:"status"`
	StartDate     sql.NullTime      `json:"start_date"`
	EndDate       sql.NullTime      `json:"end_date"`
	PartsCostPln  string            `json:"parts_cost_pln"`
	LaborCostPln  string            `json:"labor_cost_pln"`
	TotalCostPln  sql.NullString    `json:"total_cost_pln"`
	Description   sql.NullString    `json:"description"`
}

func (q *Queries) ListVehicleMaintenanceHistory(ctx context.Context, arg ListVehicleMaintenanceHistoryParams) ([]ListVehicleMaintenanceHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listVehicleMaintenanceHistory,
		arg.VehicleID,
		arg.Column2,
		arg.Type,
		arg.Column4,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVehicleMaintenanceHistoryRow
	for rows.Next() {
		var i ListVehicleMaintenanceHistoryRow
		if err := rows.Scan(
			&i.MaintenanceID,
			&i.Type,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.PartsCostPln,
			&i.LaborCostPln,
			&i.TotalCostPln,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT
  vehicle_id,
  vin,
  plate_number,
  brand,
  model,
  production_year,
  capacity_kg,
  current_mileage_km,
  status,
  deleted_at,
  created_at,
  updated_at
FROM Vehicles
WHERE (? = 1 OR deleted_at IS NULL)
  AND (? = '' OR LOWER(vin) LIKE CONCAT('%', LOWER(?), '%') OR LOWER(brand) LIKE CONCAT('%', LOWER(?), '%'))
  AND (? = '' OR status = ?)
ORDER BY vehicle_id DESC
LIMIT ? OFFSET ?
`

type ListVehiclesParams struct {
	Column1 interface{}        `json:"column_1"`
	Column2 interface{}        `json:"column_2"`
	LOWER   string             `json:"LOWER"`
	LOWER_2 string             `json:"LOWER_2"`
	Column5 interface{}        `json:"column_5"`
	Status  NullVehiclesStatus `json:"status"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error) {
	rows, err := q.db.QueryContext(ctx, listVehicles,
		arg.Column1,
		arg.Column2,
		arg.LOWER,
		arg.LOWER_2,
		arg.Column5,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.VehicleID,
			&i.Vin,
			&i.PlateNumber,
			&i.Brand,
			&i.Model,
			&i.ProductionYear,
			&i.CapacityKg,
			&i.CurrentMileageKm,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreVehicleByID = `-- name: RestoreVehicleByID :execrows
UPDATE Vehicles
SET deleted_at = NULL, updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreVehicleByID(ctx context.Context, vehicleID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreVehicleByID, vehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteVehicle = `-- name: SoftDeleteVehicle :execrows
UPDATE Vehicles
SET deleted_at = NOW(), updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteVehicle(ctx context.Context, vehicleID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteVehicle, vehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVehicle = `-- name: UpdateVehicle :execrows
UPDATE Vehicles
SET
  vin = ?,
  plate_number = ?,
  brand = ?,
  model = ?,
  production_year = ?,
  capacity_kg = ?,
  current_mileage_km = ?,
  status = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleParams struct {
	Vin              string             `json:"vin"`
	PlateNumber      sql.NullString     `json:"plate_number"`
	Brand            sql.NullString     `json:"brand"`
	Model            sql.NullString     `json:"model"`
	ProductionYear   sql.NullInt16      `json:"production_year"`
	CapacityKg       sql.NullInt32      `json:"capacity_kg"`
	CurrentMileageKm sql.NullInt32      `json:"current_mileage_km"`
	Status           NullVehiclesStatus `json:"status"`
	VehicleID        int32              `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicle,
		arg.Vin,
		arg.PlateNumber,
		arg.Brand,
		arg.Model,
		arg.ProductionYear,
		arg.CapacityKg,
		arg.CurrentMileageKm,
		arg.Status,
		arg.VehicleID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateVehicleStatus = `-- name: UpdateVehicleStatus :execrows
UPDATE Vehicles
SET
  status = ?,
  updated_at = NOW()
WHERE vehicle_id = ?
  AND deleted_at IS NULL
`

type UpdateVehicleStatusParams struct {
	Status    NullVehiclesStatus `json:"status"`
	VehicleID int32              `json:"vehicle_id"`
}

func (q *Queries) UpdateVehicleStatus(ctx context.Context, arg UpdateVehicleStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateVehicleStatus, arg.Status, arg.VehicleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
