// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waypoints.sql

package sqlc

import (
	"context"
)

const countWaypointsByRouteID = `-- name: CountWaypointsByRouteID :one
SELECT COUNT(*)
FROM RouteWaypoints
WHERE route_id = ?
`

func (q *Queries) CountWaypointsByRouteID(ctx context.Context, routeID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWaypointsByRouteID, routeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWaypoint = `-- name: CreateWaypoint :execlastid
INSERT INTO RouteWaypoints (
  route_id,
  sequence_order,
  address,
  latitude,
  longitude,
  action_type
)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWaypointParams struct {
	RouteID       int32                    `json:"route_id"`
	SequenceOrder int32                    `json:"sequence_order"`
	Address       string                   `json:"address"`
	Latitude      string                   `json:"latitude"`
	Longitude     string                   `json:"longitude"`
	ActionType    RoutewaypointsActionType `json:"action_type"`
}

func (q *Queries) CreateWaypoint(ctx context.Context, arg CreateWaypointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createWaypoint,
		arg.RouteID,
		arg.SequenceOrder,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.ActionType,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteWaypoint = `-- name: DeleteWaypoint :execrows
DELETE FROM RouteWaypoints
WHERE waypoint_id = ?
`

func (q *Queries) DeleteWaypoint(ctx context.Context, waypointID int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteWaypoint, waypointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMaxSequenceOrder = `-- name: GetMaxSequenceOrder :one
SELECT COALESCE(MAX(sequence_order), 0) AS max_order
FROM RouteWaypoints
WHERE route_id = ?
`

func (q *Queries) GetMaxSequenceOrder(ctx context.Context, routeID int32) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSequenceOrder, routeID)
	var max_order interface{}
	err := row.Scan(&max_order)
	return max_order, err
}

const getWaypointByID = `-- name: GetWaypointByID :one
SELECT
  waypoint_id,
  route_id,
  sequence_order,
  address,
  latitude,
  longitude,
  action_type
FROM RouteWaypoints
WHERE waypoint_id = ?
LIMIT 1
`

func (q *Queries) GetWaypointByID(ctx context.Context, waypointID int32) (Routewaypoint, error) {
	row := q.db.QueryRowContext(ctx, getWaypointByID, waypointID)
	var i Routewaypoint
	err := row.Scan(
		&i.WaypointID,
		&i.RouteID,
		&i.SequenceOrder,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.ActionType,
	)
	return i, err
}

const getWaypointRouteID = `-- name: GetWaypointRouteID :one
SELECT route_id
FROM RouteWaypoints
WHERE waypoint_id = ?
LIMIT 1
`

func (q *Queries) GetWaypointRouteID(ctx context.Context, waypointID int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getWaypointRouteID, waypointID)
	var route_id int32
	err := row.Scan(&route_id)
	return route_id, err
}

const listWaypointIDsByRouteID = `-- name: ListWaypointIDsByRouteID :many
SELECT waypoint_id, sequence_order
FROM RouteWaypoints
WHERE route_id = ?
ORDER BY sequence_order ASC
`

type ListWaypointIDsByRouteIDRow struct {
	WaypointID    int32 `json:"waypoint_id"`
	SequenceOrder int32 `json:"sequence_order"`
}

func (q *Queries) ListWaypointIDsByRouteID(ctx context.Context, routeID int32) ([]ListWaypointIDsByRouteIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listWaypointIDsByRouteID, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaypointIDsByRouteIDRow
	for rows.Next() {
		var i ListWaypointIDsByRouteIDRow
		if err := rows.Scan(&i.WaypointID, &i.SequenceOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaypointsByRouteID = `-- name: ListWaypointsByRouteID :many
SELECT
  waypoint_id,
  route_id,
  sequence_order,
  address,
  latitude,
  longitude,
  action_type
FROM RouteWaypoints
WHERE route_id = ?
ORDER BY sequence_order ASC
`

func (q *Queries) ListWaypointsByRouteID(ctx context.Context, routeID int32) ([]Routewaypoint, error) {
	rows, err := q.db.QueryContext(ctx, listWaypointsByRouteID, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Routewaypoint
	for rows.Next() {
		var i Routewaypoint
		if err := rows.Scan(
			&i.WaypointID,
			&i.RouteID,
			&i.SequenceOrder,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.ActionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renumberWaypointsAfterDelete = `-- name: RenumberWaypointsAfterDelete :exec
UPDATE RouteWaypoints
SET sequence_order = sequence_order - 1
WHERE route_id = ?
  AND sequence_order > ?
`

type RenumberWaypointsAfterDeleteParams struct {
	RouteID       int32 `json:"route_id"`
	SequenceOrder int32 `json:"sequence_order"`
}

func (q *Queries) RenumberWaypointsAfterDelete(ctx context.Context, arg RenumberWaypointsAfterDeleteParams) error {
	_, err := q.db.ExecContext(ctx, renumberWaypointsAfterDelete, arg.RouteID, arg.SequenceOrder)
	return err
}

const updateWaypoint = `-- name: UpdateWaypoint :execrows
UPDATE RouteWaypoints
SET
  sequence_order = ?,
  address = ?,
  latitude = ?,
  longitude = ?,
  action_type = ?
WHERE waypoint_id = ?
`

type UpdateWaypointParams struct {
	SequenceOrder int32                    `json:"sequence_order"`
	Address       string                   `json:"address"`
	Latitude      string                   `json:"latitude"`
	Longitude     string                   `json:"longitude"`
	ActionType    RoutewaypointsActionType `json:"action_type"`
	WaypointID    int32                    `json:"waypoint_id"`
}

func (q *Queries) UpdateWaypoint(ctx context.Context, arg UpdateWaypointParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWaypoint,
		arg.SequenceOrder,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.ActionType,
		arg.WaypointID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWaypointSequence = `-- name: UpdateWaypointSequence :execrows
UPDATE RouteWaypoints
SET sequence_order = ?
WHERE waypoint_id = ?
`

type UpdateWaypointSequenceParams struct {
	SequenceOrder int32 `json:"sequence_order"`
	WaypointID    int32 `json:"waypoint_id"`
}

func (q *Queries) UpdateWaypointSequence(ctx context.Context, arg UpdateWaypointSequenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWaypointSequence, arg.SequenceOrder, arg.WaypointID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
