-- Generated by scripts/generate_audit_triggers.py
-- Drops triggers created by 000022_expand_audit_triggers.

DROP TRIGGER IF EXISTS trg_users_audit_insert;
DROP TRIGGER IF EXISTS trg_users_audit_update;
DROP TRIGGER IF EXISTS trg_users_audit_delete;

DROP TRIGGER IF EXISTS trg_drivers_audit_insert;
DROP TRIGGER IF EXISTS trg_drivers_audit_update;
DROP TRIGGER IF EXISTS trg_drivers_audit_delete;

DROP TRIGGER IF EXISTS trg_vehicles_audit_insert;
DROP TRIGGER IF EXISTS trg_vehicles_audit_update;
DROP TRIGGER IF EXISTS trg_vehicles_audit_delete;

DROP TRIGGER IF EXISTS trg_clients_audit_insert;
DROP TRIGGER IF EXISTS trg_clients_audit_update;
DROP TRIGGER IF EXISTS trg_clients_audit_delete;

DROP TRIGGER IF EXISTS trg_orders_audit_insert;
DROP TRIGGER IF EXISTS trg_orders_audit_update;
DROP TRIGGER IF EXISTS trg_orders_audit_delete;

DROP TRIGGER IF EXISTS trg_routes_audit_insert;
DROP TRIGGER IF EXISTS trg_routes_audit_update;
DROP TRIGGER IF EXISTS trg_routes_audit_delete;

DROP TRIGGER IF EXISTS trg_routewaypoints_audit_insert;
DROP TRIGGER IF EXISTS trg_routewaypoints_audit_update;
DROP TRIGGER IF EXISTS trg_routewaypoints_audit_delete;

DROP TRIGGER IF EXISTS trg_cargo_audit_insert;
DROP TRIGGER IF EXISTS trg_cargo_audit_update;
DROP TRIGGER IF EXISTS trg_cargo_audit_delete;

DROP TRIGGER IF EXISTS trg_trips_audit_insert;
DROP TRIGGER IF EXISTS trg_trips_audit_update;
DROP TRIGGER IF EXISTS trg_trips_audit_delete;

DROP TRIGGER IF EXISTS trg_assignments_audit_insert;
DROP TRIGGER IF EXISTS trg_assignments_audit_update;
DROP TRIGGER IF EXISTS trg_assignments_audit_delete;

DROP TRIGGER IF EXISTS trg_fuel_logs_audit_insert;
DROP TRIGGER IF EXISTS trg_fuel_logs_audit_update;
DROP TRIGGER IF EXISTS trg_fuel_logs_audit_delete;

DROP TRIGGER IF EXISTS trg_maintenance_audit_insert;
DROP TRIGGER IF EXISTS trg_maintenance_audit_update;
DROP TRIGGER IF EXISTS trg_maintenance_audit_delete;

DROP TRIGGER IF EXISTS trg_insurance_policies_audit_insert;
DROP TRIGGER IF EXISTS trg_insurance_policies_audit_update;
DROP TRIGGER IF EXISTS trg_insurance_policies_audit_delete;
