-- Generated by scripts/generate_audit_triggers.py
-- Drops triggers created by 000022_expand_audit_triggers.

DROP TRIGGER IF EXISTS trg_users_audit_insert;
DROP TRIGGER IF EXISTS trg_users_audit_update;
DROP TRIGGER IF EXISTS trg_users_audit_delete;

DROP TRIGGER IF EXISTS trg_drivers_audit_insert;
DROP TRIGGER IF EXISTS trg_drivers_audit_update;
DROP TRIGGER IF EXISTS trg_drivers_audit_delete;

DROP TRIGGER IF EXISTS trg_vehicles_audit_insert;
DROP TRIGGER IF EXISTS trg_vehicles_audit_update;
DROP TRIGGER IF EXISTS trg_vehicles_audit_delete;

DROP TRIGGER IF EXISTS trg_clients_audit_insert;
DROP TRIGGER IF EXISTS trg_clients_audit_update;
DROP TRIGGER IF EXISTS trg_clients_audit_delete;

DROP TRIGGER IF EXISTS trg_orders_audit_insert;
DROP TRIGGER IF EXISTS trg_orders_audit_update;
DROP TRIGGER IF EXISTS trg_orders_audit_delete;

DROP TRIGGER IF EXISTS trg_routes_audit_insert;
DROP TRIGGER IF EXISTS trg_routes_audit_update;
DROP TRIGGER IF EXISTS trg_routes_audit_delete;

DROP TRIGGER IF EXISTS trg_routewaypoints_audit_insert;
DROP TRIGGER IF EXISTS trg_routewaypoints_audit_update;
DROP TRIGGER IF EXISTS trg_routewaypoints_audit_delete;

DROP TRIGGER IF EXISTS trg_cargo_audit_insert;
DROP TRIGGER IF EXISTS trg_cargo_audit_update;
DROP TRIGGER IF EXISTS trg_cargo_audit_delete;

DROP TRIGGER IF EXISTS trg_trips_audit_insert;
DROP TRIGGER IF EXISTS trg_trips_audit_update;
DROP TRIGGER IF EXISTS trg_trips_audit_delete;

DROP TRIGGER IF EXISTS trg_assignments_audit_insert;
DROP TRIGGER IF EXISTS trg_assignments_audit_update;
DROP TRIGGER IF EXISTS trg_assignments_audit_delete;

DROP TRIGGER IF EXISTS trg_FuelLog_audit_insert;
DROP TRIGGER IF EXISTS trg_FuelLog_audit_update;
DROP TRIGGER IF EXISTS trg_FuelLog_audit_delete;

DROP TRIGGER IF EXISTS trg_maintenance_audit_insert;
DROP TRIGGER IF EXISTS trg_maintenance_audit_update;
DROP TRIGGER IF EXISTS trg_maintenance_audit_delete;

DROP TRIGGER IF EXISTS trg_InsurancePolicy_audit_insert;
DROP TRIGGER IF EXISTS trg_InsurancePolicy_audit_update;
DROP TRIGGER IF EXISTS trg_InsurancePolicy_audit_delete;

-- Restore original changelog triggers dropped by 000022_up
CREATE TRIGGER trg_FuelLog_changelog_insert AFTER INSERT ON FuelLog FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'FuelLog', NEW.id, 'INSERT', NULL, JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'total_cost', NEW.total_cost), NOW());

CREATE TRIGGER trg_FuelLog_changelog_update AFTER UPDATE ON FuelLog FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'FuelLog', NEW.id, 'UPDATE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'total_cost', OLD.total_cost), JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'total_cost', NEW.total_cost), NOW());

CREATE TRIGGER trg_FuelLog_changelog_delete AFTER DELETE ON FuelLog FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'FuelLog', OLD.id, 'DELETE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'total_cost', OLD.total_cost), NULL, NOW());

CREATE TRIGGER trg_InsurancePolicy_changelog_insert AFTER INSERT ON InsurancePolicy FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'InsurancePolicy', NEW.id, 'INSERT', NULL, JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'type', NEW.type), NOW());

CREATE TRIGGER trg_InsurancePolicy_changelog_update AFTER UPDATE ON InsurancePolicy FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'InsurancePolicy', NEW.id, 'UPDATE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'type', OLD.type), JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'type', NEW.type), NOW());

CREATE TRIGGER trg_InsurancePolicy_changelog_delete AFTER DELETE ON InsurancePolicy FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'InsurancePolicy', OLD.id, 'DELETE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'type', OLD.type), NULL, NOW());

CREATE TRIGGER trg_Cost_changelog_insert AFTER INSERT ON Cost FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'Cost', NEW.id, 'INSERT', NULL, JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'category', NEW.category, 'amount', NEW.amount), NOW());

CREATE TRIGGER trg_Cost_changelog_update AFTER UPDATE ON Cost FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'Cost', NEW.id, 'UPDATE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'category', OLD.category, 'amount', OLD.amount), JSON_OBJECT('id', NEW.id, 'vehicle_id', NEW.vehicle_id, 'category', NEW.category, 'amount', NEW.amount), NOW());

CREATE TRIGGER trg_Cost_changelog_delete AFTER DELETE ON Cost FOR EACH ROW
INSERT INTO Changelog (user_id, table_name, record_id, operation, old_data, new_data, timestamp)
VALUES (@current_user_id, 'Cost', OLD.id, 'DELETE', JSON_OBJECT('id', OLD.id, 'vehicle_id', OLD.vehicle_id, 'category', OLD.category, 'amount', OLD.amount), NULL, NOW());
